### ISSUE TITLE
Discussion Question: Forested Areas and Terrain - Drag Based Models

### ISSUE THREAD

**Issue by hgopalan** [Exawind/amr-wind#1002]
I wanted to start a discussion on the inclusion of forested areas and Terrain using simple drag based models. The most common method for inclusion of trees uses the drag force model 

F_i = - Cd LAD(z) AF |u_i| u_i 

C_d - Drag coefficient, LAD - Leaf area density ; AF - Area fraction covered by trees. 

Trees are usually represented by rectangular boxes and it is straight-forward to include them. 

The drag model has also been applied to buildings as demonstrated in Fast-Eddy by modifying the force term as follows: 

F_i = - alpha_m  AF / Delta  |u_i| u_i 

where alpha_m is a constant and Delta is cell size function. 

Ref:  https://doi.org/10.1029/2020MS002141

This method can also be in-principle used for terrains by marking cells to apply the forcing. I noticed the possibility of including STL for EB methods in AMREX. How easy will it be to access the classes within the AMR-Wind framework?

**Comment by marchdf** [comment]
A couple of thoughts:
- we have a "discussion" tab for this repo so maybe it makes more sense to move this discussion there ;) 
- Do I understand that you want to use the EB capability to "tag" cells using an STL geometry? And then apply a forcing in those cells? There might be an easier way to do that...

**Comment by hgopalan** [comment]
Will do it next time :). 

Yes. I want to evaluate  immersed solid method and apply the forcing to the tagged cells.
