### ISSUE TITLE
MPI link warnings with CUDA

### ISSUE THREAD

**Issue by jrood-nrel** [Exawind/amr-wind#101]
Does anybody know why there are so many link warnings with undefined MPI references ever since 31b8508f4e194b7a0fb5ac73edc5b1e0279deb3d ?

**Comment by sayerhs** [comment]
@jrood-nrel The CDash test you're referring to is April 25, the test before that is for April 16. On 16th it tested 2c5362d0d23db and then the next test was for version 31b8508. In between we updated AMReX submodule snapshot. I suspect that is the reason for these warnings.

**Comment by jrood-nrel** [comment]
The link errors started happening some time after 31b8508f4e194b7a0fb5ac73edc5b1e0279deb3d

**Comment by sayerhs** [comment]
Can you show me the CDash output for the commit before that?

**Comment by jrood-nrel** [comment]
31b8508f4e194b7a0fb5ac73edc5b1e0279deb3d is fine. Looking further into this 668310215e1ffc9cfe823fe5ca270c0734914e4d is fine too. Some time between 73ef52b0a10091f6b03fcebfc14d536c2684b365 and dcad5c1510652e0f869e02bc87a22493fae39675 these warnings appeared. It seems like 73ef52b0a10091f6b03fcebfc14d536c2684b365 is most likely.

**Comment by sayerhs** [comment]
Yes, it seems like 73ef52b is the culprit, and 668310215e1ffc is clean. Isn't immediately obvious why that commit causes these warnings.

**Comment by sayerhs** [comment]
@jrood-nrel So I can confirm that the following diff makes the warnings go away. So it seems like we still need to keep around Fortran for MPI. 

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f792636..8edb2b9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,7 +1,7 @@
 ############################ BASE ######################################

 cmake_minimum_required (VERSION 3.14 FATAL_ERROR)
-project(AMR-Wind CXX C)
+project(AMR-Wind CXX C Fortran)
 list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake")
 include(CMakePackageConfigHelpers)
```

**Comment by jrood-nrel** [comment]
Ok thanks. I put it back in.
