### ISSUE TITLE
Averaging (Post Processing AMR Wind)

### ISSUE THREAD

**Issue by AsimUdel** [Exawind/amr-wind#1013]
Hi All,
I am sorry if I am asking a silly question, I want to see the "Time Averaging" feature of AMR-Wind to see the mean velocity across different planes (I tried to plot using mean velocity of sampling (plane) across all iteration but data was too big I could not using Jupyter notebook), that's why I wanted to explore the Averaging of AMR-Wind, the problem I am facing is that using https://github.com/lawrenceccheung/ALCC_Frontier_WindFarm/blob/main/precursor/MedWS_LowTI/postprocessing/HubHeight_Viz.ipynb
template (by @lawrenceccheung ) I could only access sampling postprocessing not averaging("db     = ppsamplexr.getPlaneXR(amrdir+ncfile, iters, varnames, groupname='xy_hub', verbose=0" could only access sampling due to default python files of AMR-Wind-Frontend ). Does someone  I am attaching my input file.
[input_file_amr_wind.txt](https://github.com/Exawind/amr-wind/files/14842772/input_file_amr_wind.txt)
 Thanks in advance

**Comment by marchdf** [comment]
This feels like an issue for https://github.com/Exawind/amr-wind-frontend and not amr-wind? Maybe we can move it there?

**Comment by AsimUdel** [comment]
Hi @marchdf , Kindly close this issue as I have found the solution from (lawrence's)(https://github.com/lawrenceccheung/ALCC_Frontier_WindFarm/blob/main/precursor/MedWS_LowTI/postprocessing/Test_MinMaxStd_PlaneXR.ipynb) , @lawrenceccheung thank you so much, I will definitely look into that.
