### ISSUE TITLE
FLLC Reintroduced bug

### ISSUE THREAD

**Issue by tonyinme** [Exawind/amr-wind#1038]
There was a bug introduced [here](https://github.com/Exawind/amr-wind/blame/bdddf133e41a9b7b4c8ce28f1ea1bebec47678f5/amr-wind/wind_energy/actuator/turbine/fast/turbine_fast_ops.H#L246).

This looks like it was an issue that had been fixed [here](https://github.com/Exawind/amr-wind/pull/894/files) but was reintroduced as part of another PR.

**Comment by mbkuhn** [comment]
I'm pretty sure that this bug was fixed by #1043. @tonyinme @marchdf can we confirm?
