### ISSUE TITLE
Encountered NetCDF error; aborting

### ISSUE THREAD

**Issue by AsimUdel** [Exawind/amr-wind#1071]
Hello, 
I am want to run a simulation for my research but I am constantly getting this error
"terminate called after throwing an instance of 'std::runtime_error'
  what():  Encountered NetCDF error; aborting" 
after that my simulation is aborted every time. I am attaching my input file and error log file in the attachment.
[Error_output_file.txt](https://github.com/Exawind/amr-wind/files/15419144/Error_output_file.txt)
[Spinup_unstable_wind_energy.txt](https://github.com/Exawind/amr-wind/files/15419145/Spinup_unstable_wind_energy.txt)

**Comment by marchdf** [comment]
These look like old versions of the software stack (v1 amr-wind and v3.1 openfast). Any chance we can get you to update it? 

One way I would suggest you debug this is by selectively commenting out the sampling section of your input file and then slowly adding it bit by bit until you can narrow down what is breaking. It looks like a name/string matching problem:
```
NetCDF: String match to name in use
```

**Comment by moprak-nrel** [comment]
The issue here is that you seem to have `xy` twice in the `sampling.labels = xy xz xy` field.  You also appear to be using an older version of `AMR-wind` and I believe this should be fixed in the newer versions.

**Comment by marchdf** [comment]
I can confirm that changing `sampling.labels = xy xz xy` to `sampling.labels = xy xz yz` fixes the issue.

**Comment by AsimUdel** [comment]
@moprak-nrel thank you for the catch, @marchdf yes, I can also confirm, simulation started perfectly. Regarding using the older versions of AMR-Wind and OpenFAST, I was not aware of the newer version of an AMR-Wind has released and (I was told that v 3.1.0 of OpenFAST is compatible with that v. of AMR-Wind. Please guide me in this regard.

**Comment by moprak-nrel** [comment]
Glad it solved your issue. We are currently at AMR-Wind, 2.x, which comes with a lot of features and some critical bugfixes. It should be compatible with versions of OpenFAST 3.5.*. We highly encourage you to switch to the newer release.  

You can read the release notes here for more info: https://github.com/Exawind/amr-wind/releases

**Comment by AsimUdel** [comment]
Thank you so much for the detail. I will switch to the newest version soon.
