### ISSUE TITLE
I encountered the following problems in the process of learning to use TurbineFASTLine. Is this due to the version of TurbineFastline

### ISSUE THREAD

**Issue by Chengyue810** [Exawind/amr-wind#1088]
I encountered the following problems in the process of learning to use TurbineFASTLine. Is this due to the version of TurbineFastline

              AMR-Wind (https://github.com/exawind/amr-wind)

  AMR-Wind version :: v2.1.0-18-gf43b0713
  AMR-Wind Git SHA :: f43b071303b755ff994e8346e028a27f326723de
  AMReX version    :: 24.05-20-g5d02c6480a0d

  Exec. time       :: Mon Jun  3 20:06:01 2024
  Build time       :: Jun  3 2024 01:13:25
  C++ compiler     :: GNU 11.4.0

  MPI              :: OFF
  GPU              :: OFF
  OpenMP           :: OFF

  No additional third-party libraries enabled

           This software is released under the BSD 3-clause license.
 See https://github.com/Exawind/amr-wind/blob/development/LICENSE for details.
------------------------------------------------------------------------------

Initializing AMReX (24.05-20-g5d02c6480a0d)...
AMReX (24.05-20-g5d02c6480a0d) initialized
Initializing AMR-Wind ...
Initializing boundary conditions for velocity_mueff
Initializing boundary conditions for velocity
Initializing boundary conditions for density
Initializing boundary conditions for p
Initializing boundary conditions for velocity_src_term
Initializing boundary conditions for gp
Creating PDESystem instance: ICNS-Godunov
Creating Physics instance: FreeStream
Creating Physics instance: Actuator
Creating TurbulenceModel instance: Laminar-ConstTransport
Creating RefinementCriteria instance: GeometryRefinement
(-200 -200 -200)
(200 -200 -200)
(200 200 -200)
(-200 200 -200)
(-200 -200 200)
(200 -200 200)
(200 200 200)
(-200 200 200)
Creating GeometryType instance: box
Creating PostProcessBase instance: Sampling
Initializing I/O manager
Creating UDF instance: ConstValue
Creating UDF instance: ConstValue
ActuatorModel 4
 - UniformCtDisk
 - FixedWingLine
 - JoukowskyDisk
 - FlatPlateLine
terminate called after throwing an instance of 'std::runtime_error'
  what():  In ActuatorModel cannot find instance: TurbineFastLine
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node DESKTOP-KJ7DS8K exited on signal 6 (Aborted).
--------------------------------------------------------------------------

**Comment by justhawk98** [comment]
In order to use TurbineFastLine, you need to compile with the OpenFAST flag on. If you're compiling from source, this can be done with the following commands:

cd path/to/amr-wind/source/code
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/PATH/TO/DESIRED/INSTALL/LOCATION -DAMR_WIND_ENABLE_OPENFAST=ON -DOpenFAST_DIR=PATH/TO/OPENFAST/INSTALL/DIRECTORY/lib/cmake/OpenFAST  -DAMR_WIND_ENABLE_MPI=ON

You can turn the MPI flag off if you want. [But as I recently learned, you need it on if you'll be running more than one turbine.](https://github.com/Exawind/amr-wind/issues/1068#issuecomment-2145791669)

**Comment by Chengyue810** [comment]
Thank you very much for your reply, I have solved the above problem, but it still ends abnormally. Is it due to NetCDF not compiling correctly, although I thought I took this part into account during the compilation process

 
 OpenFAST input file heading:
     FAST Certification Test #01: NREL 5.0 MW Baseline Wind Turbine (Onshore)

 Running ElastoDyn.
 Nodal outputs section of ElastoDyn input file not found or improperly formatted.
 Running AeroDyn.
 Using uniform blade force node clustering.
OpenFAST model does not include tower for turbine: WTG01 Turning off tower actuator points
WARNING: FastIface: NetCDF support was not enabled during compile time. FastIface cannot support restart.
 T0 Time: 0 of 500 seconds.
Creating MomentumSource instance: ActuatorForcing
Creating SamplerBase instance: PlaneSampler
Creating SamplerBase instance: LineSampler
Creating SamplerBase instance: LineSampler
Creating SamplerBase instance: LineSampler
Creating SamplerBase instance: LineSampler
Creating SamplerBase instance: LineSampler
Creating SamplerBase instance: LineSampler
Creating SamplerBase instance: LineSampler
Begin initial projection
[DESKTOP-KJ7DS8K:12669] *** Process received signal ***
[DESKTOP-KJ7DS8K:12669] Signal: Segmentation fault (11)
[DESKTOP-KJ7DS8K:12669] Signal code: Invalid permissions (2)
[DESKTOP-KJ7DS8K:12669] Failing at address: 0x7fd0470d0008
[DESKTOP-KJ7DS8K:12669] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fdfa8b62520]
[DESKTOP-KJ7DS8K:12669] [ 1] /lib/x86_64-linux-gnu/libc.so.6(+0xa33f3)[0x7fdfa8bc33f3]
[DESKTOP-KJ7DS8K:12669] [ 2] /lib/x86_64-linux-gnu/libc.so.6(+0xa48dd)[0x7fdfa8bc48dd]
[DESKTOP-KJ7DS8K:12669] [ 3] /lib/x86_64-linux-gnu/libc.so.6(malloc+0x99)[0x7fdfa8bc5139]
[DESKTOP-KJ7DS8K:12669] [ 4] /home/chy/amr-wind/build/amr_wind(+0x80c596)[0x7fdfa9e0d596]
[DESKTOP-KJ7DS8K:12669] [ 5] /home/chy/amr-wind/build/amr_wind(+0x149b7b)[0x7fdfa974ab7b]
[DESKTOP-KJ7DS8K:12669] [ 6] /home/chy/amr-wind/build/amr_wind(+0x8190e7)[0x7fdfa9e1a0e7]
[DESKTOP-KJ7DS8K:12669] [ 7] /home/chy/amr-wind/build/amr_wind(+0x910e80)[0x7fdfa9f11e80]
[DESKTOP-KJ7DS8K:12669] [ 8] /home/chy/amr-wind/build/amr_wind(+0x935e7b)[0x7fdfa9f36e7b]
[DESKTOP-KJ7DS8K:12669] [ 9] /home/chy/amr-wind/build/amr_wind(+0x36cbd4)[0x7fdfa996dbd4]
[DESKTOP-KJ7DS8K:12669] [10] /home/chy/amr-wind/build/amr_wind(+0x73eb96)[0x7fdfa9d3fb96]
[DESKTOP-KJ7DS8K:12669] [11] /home/chy/amr-wind/build/amr_wind(+0x1424b8)[0x7fdfa97434b8]
[DESKTOP-KJ7DS8K:12669] [12] /home/chy/amr-wind/build/amr_wind(+0x14d117)[0x7fdfa974e117]
[DESKTOP-KJ7DS8K:12669] [13] /home/chy/amr-wind/build/amr_wind(+0x7655d)[0x7fdfa967755d]
[DESKTOP-KJ7DS8K:12669] [14] /home/chy/amr-wind/build/amr_wind(+0x61465)[0x7fdfa9662465]
[DESKTOP-KJ7DS8K:12669] [15] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7fdfa8b49d90]
[DESKTOP-KJ7DS8K:12669] [16] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7fdfa8b49e40]
[DESKTOP-KJ7DS8K:12669] [17] /home/chy/amr-wind/build/amr_wind(+0x6da25)[0x7fdfa966ea25]
[DESKTOP-KJ7DS8K:12669] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node DESKTOP-KJ7DS8K exited on signal 11 (Segmentation fault).

**Comment by justhawk98** [comment]
NetCDF might be the problem. I think the sampling feature might choose the netcdf format by [default.](https://exawind.github.io/amr-wind/user/inputs_Sampling.html) . What if you comment out all your sampling lines from the input files? Does it work then?

**Comment by marchdf** [comment]
Have you been able to follow the above suggestion and are you still facing this problem?

**Comment by marchdf** [comment]
Closing as the suggested fix was given and appears to have worked for this issue. There appears to be a build problem in not enabling netcdf. Please reopen if this is still an issue.
