### ISSUE TITLE
Representing an obstacle through a local transition in surface roughness

### ISSUE THREAD

**Issue by delloiaconobenito** [Exawind/amr-wind#1110]
Hi everyone, I am trying to run a case with some obstacles in front of wind turbines. I would like to know if there is a way, other than the Immersed Boundary technique, to implement an obstacle. Can this be done by locally varying the surface roughness parameter z0?

**Comment by hgopalan** [comment]
I have two on-going developments to represent an obstacle: (I) an immersed forcing method to explicitly specify a region of blockage through STL/DEM file and (II) Modifying the ABLWallFunction.cpp to impose a heterogenous roughness through a user-specified or NLCD database and apply the wall function. The first method is stable and I should create a PR for it soon. The second one will need some more time and will let you know when I have an initial draft.

**Comment by delloiaconobenito** [comment]
Thank you! I am looking forward to your updates.

**Comment by delloiaconobenito** [comment]
At the moment I am using some boxes as obstacles, which seem to be already implemented. The problem is that if I specify more than one IB in my input file the solver only treats the last one, as if overwriting the previous ones. Do you know why? 
I attach my input file so you can see if I am making any mistakes with the input file.
[IBbox_input.txt](https://github.com/user-attachments/files/16021832/IBbox_input.txt)

**Comment by delloiaconobenito** [comment]
I have tried representing the obstacles with other geometries (spheres or cylinders) and it works. So it seems that the problem is related only to the immersed boundary box type.

**Comment by marchdf** [comment]
I am going to close this since you opened a specific issue regarding your last point here: https://github.com/Exawind/amr-wind/issues/1117
