### ISSUE TITLE
Calculation of flow field in complex terrain

### ISSUE THREAD

**Issue by CaiZhiming-HHU** [Exawind/amr-wind#1114]
Dear all，
I would like to ask how to use amr-wind to calculate the 3D flow field under the custom complex terrain? After calculating the flow field, I want to sample the whole field and export the wind speed data in vtk format. I would appreciate if there's a manual or case code and instructions!

**Comment by hgopalan** [comment]
What do you mean by custom complex terrain? Can you provide more details of your setup and test case?

**Comment by CaiZhiming-HHU** [comment]
To be honest, I am a PhD student in the wind power research, using FAST.Farm in complex terrain of the flow field research.
In https://github.com/OpenFAST/openfast/issues/1027, jjonkman is put forward👇
![image](https://github.com/Exawind/amr-wind/assets/89171153/79c7bccf-7619-41d8-9935-f2bad2fa7cf8)
Therefore, I hope to use amr-wind as the precursor of the background inflow simulation of wind farm, and derive the calculated background inflow wind speed information as the inflow of FAST.Farm.
However, I did not find the relevant operation instructions in the amr-wind documentation, so I would like to ask you.

**Comment by rthedin** [comment]
Related to https://github.com/OpenFAST/openfast/issues/2298.

I'm not sure if you are seeking more information on how to run complex terrain on AMR-Wind or how to sample data and convert them to use in FAST.Farm. If the former, @hgopalan will be able to help you; if the latter, I've covered it in my response to the issue linked above.

**Comment by CaiZhiming-HHU** [comment]
Thanks for your reply! In fact, I am seeking both the former and the latter.

**Comment by hgopalan** [comment]
We are still in the experiment phase of testing terrain with arm-wind + FAST.Farm. Once we have a working case, we will share it here for your use. 


Terrain feature in amr-wind without FAST.Farm support should be available in a future release.

**Comment by hgopalan** [comment]
Your request will be addressed by #1115 . I will close this issue for now.
