### ISSUE TITLE
Unable to represent more than one Box type with the Immersed Boundary method

### ISSUE THREAD

**Issue by delloiaconobenito** [Exawind/amr-wind#1117]
Hello, I am trying to run a case with some obstacles in front of wind turbines. At the moment I am using the existing immersed boundary method, representing the obstacle with a box geometry type. 
The problem is that if I specify more than one box in my input file only the last one is considered in the simulation. However, I can do this with the other types of geometry (sphere or cylinder) without any problem. Do you know why I am encountering this problem?
I attach my input file so you can see if I am making any mistakes.
[IBbox_input.txt](https://github.com/user-attachments/files/16100829/IBbox_input.txt)

**Comment by marchdf** [comment]
I do think I know what is going on. In the sphere/cylinder, there is a check on the previous value of the levelset. Not so for box. I think it's a simple fix. Hang tight.

**Comment by delloiaconobenito** [comment]
Thank you!
