### ISSUE TITLE
Potential unidentified bug causes an asymmetry in the solution field

### ISSUE THREAD

**Issue by mukul1992** [Exawind/amr-wind#1126]
## Bug description
While working with the new in-out BC #1066 and the associated test that has two z-layers of the flow going in opposite directions, I noticed an unexpected asymmetry developing in the second time step. To isolate the issue, I reproduced it with the `mass_inflow` BC. I also tried to create a clean test case which does not rely on the new "two-layer" UDF but wasn't immediately able to reproduce the issue. 

## Steps to reproduce

1. Clone and checkout the [erf-model:inoutbc branch](https://github.com/erf-model/amr-wind/tree/inoutbc). I understand that this is not ideal. I am willing to work with the developers on creating a test case which does not rely on unmerged developments.
2. Compile `amr_wind`, go to the `bctest` directory, and run the `input_inflow` case.

An asymmetry develops in the x- and z-velocity fields in time step 2. Although it doesn't show up in the min/max values printed here, the first place I see it is in the u_mac field before the projection.
![Screenshot 2024-07-09 at 4 57 24 PM](https://github.com/Exawind/amr-wind/assets/18251677/4fd47d7b-f042-49d8-8937-2af433a298cf)

## Expected behavior
Since the imposed conditions are symmetric in x and z-directions, I did not expect an asymmetry. As this is happening with the `mass_inflow` BCs too, it may indicate some issue in the MAC-velocity calculations that is not related to the new in-out BC.

**Comment by asalmgren** [comment]
@mukul1992 -- your output snippet says it is velocities after the MAC projection -- I just want to confirm that you have confirmed you see the differences before the MAC projection?  (You do say "before" so just confirming)

**Comment by mukul1992** [comment]
Yes I see it before the projection. Just that the max min values don't show
that.

Mukul Dave
Ph: (+1) 512-817-8939
E-mail: ***@***.***
View my profile: http://www.linkedin.com/in/mukuldave

**Comment by marchdf** [comment]
Thanks for detailing this issue. Is there a way you can pull out the test case from the branch you refer to and check that you get the same behavior with just that test case + main branch (and the mass outflow)? Basically keeping the diffs to a minimum. Does my question make sense?

**Comment by mukul1992** [comment]
@marchdf Ann, I, and Michael discussed that Ann and I can try to debug this while you and Michael work on the boundary fill routines. We did make some headway and seem to have narrowed it down a bit. We'll keep you updated.
