### ISSUE TITLE
Sampling resolved TKE on a plane

### ISSUE THREAD

**Issue by delloiaconobenito** [Exawind/amr-wind#1127]
Hi everyone, I want to output the resolved TKE field on a sampling plane. How can I do this? I found the sampling field "tke" but it seems to refer to TKE on a subgrid scale.

**Comment by hgopalan** [comment]
I don't think there is a direct way to compute resolved TKE field. An external fix will be using the output data planes to manually calculate it from the wind speeds. 

Rxx=\timeAverage(Ux Ux) - \timeAverage(Ux) \timeAverage(Ux) 
Ryy=\timeAverage(Uy Uy) - \timeAverage(Uy) \timeAverage(Uy) 
Rzz=\timeAverage(Uz Uz) - \timeAverage(Uz) \timeAverage(Uz) 

TKE = 0.5 * ( Rxx + Ryy + Rzz)

**Comment by moprak-nrel** [comment]
There is a slightly easier way from the stats outputs, the fields :   `"u'u'_r", "v'v'_r", "w'w'_r"` contain the resolved, fluctuating stress components. So you'd just need to sum these and add a `0.5` factor to get the resolved TKE.

Let us know if for some reason this doesn't work for you and I'll look into adding a resolved TKE output directly.

**Comment by rybchuk** [comment]
I personally lean towards calculating resolved TKE as a postprocessing step. I'll add one thing to hgopalan's comment: when calculating TKE, you need to first calculate some sort of average and then calculate fluctuations from that average. You can chose to time average like he did, or sometimes people will grab one instantaneous 2D snapshot and calculate against spatial averages.

**Comment by moprak-nrel** [comment]
It comes to a difference between whether you need the  resolved TKE at every timestep of the stats output or whether you want one time averaged TKE. 

For the latter, I agree with using the "ergodic mean" as a post processing step. For the former, the resolved fluctuating stressed are exactly what you need -- it is computed using the spatial averages at that timestep.

**Comment by moprak-nrel** [comment]
> There is a slightly easier way from the stats outputs, the fields : `"u'u'_r", "v'v'_r", "w'w'_r"` contain the resolved, fluctuating stress components. So you'd just need to sum these and add a `0.5` factor to get the resolved TKE.
> 
> Let us know if for some reason this doesn't work for you and I'll look into adding a resolved TKE output directly.

^I misread the issue, you're asking about TKE on sampling planes, for which Alex's answer might be the best way to do it. The above is just for ABL simulations, where you can get the resolved TKE using `ABL Stats`.

**Comment by lawrenceccheung** [comment]
Hi @delloiaconobenito,

There is a way to do it both inside the code itself, and through a postprocessing step.  There is an averaging option available in amr-wind, which can compute the Reynolds stresses as the simulation runs.  See the documentation at https://exawind.github.io/amr-wind/user/inputs_Averaging.html.  An example of how it could be set up in practice is at available https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/6311e244c9272525f8b91d55dc3ceb3dfed2be72/UnstableABL_farmrun1/UnstableABL_farmrun1.inp#L14407-L14410, just add the `ReynoldsStress` averaging type, and you can output it as a quantity to the sampling planes.

The other way to compute it is through a postprocessing step as @rybchuk suggested.  Doing it this way allows you to choose the averaging window after the fact, and also saves a bit of computation time during the simulation itself, although it does require doing an extra step.  There's a few postprocessing scripts that could be used for this -- for example, take a look at `ReynoldsStress_PlaneXR()` in https://github.com/Exawind/amr-wind-frontend/blob/main/postproamrwindsample_xarray.py.  Note that we're in the process of simplifying the postprocessing workflow, so computing TKE on sampling planes will become drastically simpler through these scripts in the very near future.

Lawrence

**Comment by marchdf** [comment]
@delloiaconobenito if the above suggestions resolve your question, would you mind closing the issue? Thanks!

**Comment by delloiaconobenito** [comment]
Thank you all. I resolved my problem with the second way proposed by @lawrenceccheung. Instead I just have a few more questions about the other methods.

- Aren't the abl stats horizontal mean profiles? In that case how can I use them to plot TKE on a specific plane?
- About the first way proposed by @lawrenceccheung, in my input file I have the Averaging post-processing with the ReynoldsStress averaging type active. What is the field name to output this quantity to a sampling plane (like velocityx, density, etc)?

**Comment by moprak-nrel** [comment]
> Aren't the abl stats horizontal mean profiles? In that case how can I use them to plot TKE on a specific plane?

Yes, they are horizontal means across the domain, so won't work for your sampling plane case.

**Comment by delloiaconobenito** [comment]
Thank you @moprak-nrel! I am closing the issue.
