### ISSUE TITLE
Overestimation of power prediction using OpenFAST/ALM for IEA-15-240-RWT

### ISSUE THREAD

**Issue by wenchaoyu** [Exawind/amr-wind#1270]
Hello the Community,

Recently when I simulated a IEA15MW reference wind turbine v1.1.11 using OpenFAST/ALM method in a neutral ABL precursor flow (U@hubheight = 8m/s, TI = 5.4%, shear = 0.12), I got an averaged power prediction 8.1MW, which is ~25% larger than the power from the design curve. I've seen the discussion in [https://github.com/Exawind/amr-wind/issues/1009](https://github.com/Exawind/amr-wind/issues/1009), and followed all the instructions to set up the epsilon (5m), actuator point number (50), grid size (2.5m), as well as the air density (incflo.density = Actuator.TurbineFastLine.density = xlo.density = 1.225).

I configurated then a uniform flow case to have a quick test (ConstValue.velocity.value = 8.0 0.0 0.0). No matter how I played with actuator point number, grid size, I always got the power around 8.35MW. Reducing the size of epsilon would decrease the power, but still got a value close to 8MW. I tried different AMR-Wind versions v1.4.0 and v3.1.4, coupled with OpenFAST v3.5.3, the results are quite similar but always overestimated. I also tried to activate fllc, but the power is getting close to 9.25MW. The final test I tried is to switch the air density back to 1.0 by using incflo.density = Actuator.TurbineFastLine.density = xlo.density = ConstValue.density.value= 1.0, air density in file .fst stays as 1.225, I got the power close to 7.08MW.

![image](https://github.com/user-attachments/assets/4f841e24-cf76-4c02-96bb-cd7d3aad7488)

Could you confirm when setting air density to 1.225, you could get a power close to the one from the design curve (6.xMW) ? If it is the case, is there any other option I might miss in amr-wind input file [alm.i.txt](https://github.com/user-attachments/files/17231371/alm.i.txt) ?

Options in OpenFAST files:
"WakeMod" is set to 0 in IEA-15-240-RWT-Monopile_AeroDyn15.dat
"CompInflow" is set to 2 in IEA-15-240-RWT-Monopile.fst

## AMR-Wind information
AMR-Wind v1.4.0 or v3.1.4
OpenFAST v3.5.3

**Comment by marchdf** [comment]
Tagging @lawrenceccheung, @ndevelder, @tonyinme, @mbkuhn as people who might have thoughts.

**Comment by tonyinme** [comment]
@wenchaoyu , thanks for bringing this to our attention. 
I have a few questions and suggestions for you to try.

1. What is the density in the OpenFAST input file (.fst) and in the Aerodyn input file?
2. Can you try running with the "wenoz" scheme as opposed to "pp_nolim" and let us know the result?
3. Can you please turn this [option](https://exawind.github.io/amr-wind/user/inputs_Actuator.html#input_param-Actuator.FixedWingLine.fllc_nonuniform) on with the filtered lifting line correction and set this [value](https://exawind.github.io/amr-wind/user/inputs_Actuator.html#input_param-Actuator.FixedWingLine.fllc_epsilon_dr_ratio) to 3?
4. Please make sure that all densities are consistent throughout the inputs and do not run simulations with different densities.  
5. Make sure than Actuator.T1.num_points_tower matches the number of tower points in the aerodyn input file.

**Comment by wenchaoyu** [comment]
Hi @tonyinme, thanks for these suggestions.
Here are the replies.

1. The density in OpenFAST input file .fst is 1.225, the one in Aerodyn is set to "default", I suppose it is the same density as in .fst.
2. I've tried it with AMR-Wind v3.1.4, with the "wenoz" as default scheme. There is a tiny variation in the mean power (8.37MW, 0.2% compared to the one got with AMR-Wind v1.4.0). You can see the power signal in the figure for constant wind 8 m/s
![image](https://github.com/user-attachments/assets/8772bfec-f463-4251-a35f-7cddc521f3c1)
3. I'll try this and get back to you when the simulation is finished
4. For the ABL case, all densities in ABL precursor, in ABL / ALM, and in .fst are the same, 1.225. For constant flow case, I used incflo.density = Actuator.TurbineFastLine.density = xlo.density = 1.225
5. Actuator.T1.num_points_tower = 20, well matched with "NumTwrNds" in aerodyn input file
6. I've tried to run the same case ([simulation.i.txt](https://github.com/user-attachments/files/17241003/simulation.i.txt)) configurated by @jfrederik-nrel in 
[https://github.com/Exawind/amr-wind/issues/1009](https://github.com/Exawind/amr-wind/issues/1009), with epsilon = 3.125, dx = 1.25, num_points_blade = 50, fllc = false, density = 1.225 (everywhere), the power is 7.15MW.

**Comment by jfrederik-nrel** [comment]
I'm not sure if it really matters (it probably shouldn't), but I did notice that you use a time step of dt=0.1. Could that possibly influence the power production? Have you tried smaller time steps to see if you get lower power?
This does very much _look_ similar to issue #1009, but as you seem to have checked the densities and @mbkuhn fixed it so AMR-Wind won't allow you to "forget" to define the density somewhere, I don't think this is actually the same issue. But 7.15MW sounds reasonable for the simulation I set up. So it seems like the issue is specifically with the run you do, not with your version of AMR-Wind.

**Comment by tonyinme** [comment]
Hi @wenchaoyu , thanks for trying those suggestions. 
I agree with @jfrederik-nrel comments, can you please try reducing the time-step and seeing if that makes a difference.
I also noticed that your domain is quite short. Can you please try to extend (at least 2X) the domain in the x direction?

**Comment by wenchaoyu** [comment]
Thanks @jfrederik-nrel and @tonyinme. Here are some updates (always with constant wind speed 8 m/s):

1. I've tried `fllc_type = variable_chord`, `fllc_nonuniform = true` with `fllc_epsilon_dr_ratio = 3`, the power is reduced from 8.35MW to 7.95MW, under the configuration `eps = 10`, `dx = 10`, `dr = 2.4`
2. I've tried `dt = 0.05` and `dt = 0.025`, their impact on the power is negligible
3. Domain size does have an impact, extending (2X) the domain in the x direction helps to converge to the power predicted with @jfrederik-nrel 's setup, 7.15MW.

When constant wind speed is 8 m/s, it seems:
1. If without fllc, a very fine mesh is required to converged to 7.1x MW (as configurated by @jfrederik-nrel: `eps = 3.125`, `dx = 1.25`, `dr = 2.4`)
2. If with fllc (`fllc_type = variable_chord`, `fllc_nonuniform = true`, `fllc_epsilon_dr_ratio = 3`), a relative coarse mesh could also converge to 7.1x MW ( with both combinations tried here `eps = 5.0`, `dx = 2.5`, `dr = 2.4` or `eps = 10`, `dx = 10`, `dr = 2.4`) 

Question:
With all the tests above, the power is getting close to 7.1x MW, but it is still ~7% larger than the power 6.68 MW got with same IEA15MW model running in OpenFAST standalone with uniform flow 8 m/s. Do I need to fine tune again `eps`, `dx`, `dr` etc to get close to 6.68MW? How do you treat the 7% difference here?

**Comment by jfrederik-nrel** [comment]
Hi @wenchaoyu,

What we ended up doing for our simulation set (and credits for this go mostly to @gyalla), is run the same simulation settings (in terms of time step, grid size, domain size) with different values of blade epsilon, and evaluate power over those runs. In our case, we ended up with an epsilon of 2.0, that resulted in very good correspondence with the power curve, see figure below. 

So yes, my advise would be to tune `eps` to get closer to the 6.68MW you are aiming for. Make sure to also check that the blade loading over the chord of the blade still looks good, for us this stopped being the case for `eps=1`.

Hope this helps,

Joeri

![image](https://github.com/user-attachments/assets/b1ec37a2-4193-403c-ab30-0cd5cc1349c6)
![image](https://github.com/user-attachments/assets/34d82a90-68f8-4132-a9ec-b376f68946b9)

**Comment by gyalla** [comment]
Thanks for sharing these figures @jfrederik-nrel. Just for clarity, the legend on the blade loading curves do not correspond to the performance metrics on the top plots. Here is a version with the legend attached for power: 

![image](https://github.com/user-attachments/assets/d7995817-75b1-412e-b522-fb8abf524b66)

**Comment by wenchaoyu** [comment]
Hi @jfrederik-nrel and @gyalla,
Thanks for sharing these figures and suggestions, it is very helpful!

**Comment by wenchaoyu** [comment]
Thanks @marchdf for the remind, it is closed now.
