### ISSUE TITLE
An error occurred while running test

### ISSUE THREAD

**Issue by May0048** [Exawind/amr-wind#1292]
The following error occurred when we ran the case in the guide. May I ask what caused it? The file is as follows
[spinup.txt](https://github.com/user-attachments/files/17376043/spinup.txt)
![1728985411401](https://github.com/user-attachments/assets/17f7d737-f757-4767-90cc-5defdfad2f30)

**Comment by hgopalan** [comment]
The error message is incomplete. Can you dump the detailed error message? It is unclear what went wrong from the snapshot.

**Comment by May0048** [comment]
This is all the operational message.
[spinuo_c.txt](https://github.com/user-attachments/files/17378319/spinuo_c.txt)

**Comment by May0048** [comment]
> The error message is incomplete. Can you dump the detailed error message? It is unclear what went wrong from the snapshot.
[spinuo_c.txt](https://github.com/user-attachments/files/17378333/spinuo_c.txt)

This is all the operational message.

**Comment by May0048** [comment]
Thanks for your reply, another error occurred after I corrected it. After checking the input file, I think the point is not outside the computational domain. The following is 
[spinuo_c1.txt](https://github.com/user-attachments/files/17380069/spinuo_c1.txt)
the running message.

**Comment by hgopalan** [comment]
The definition seems fine in spinup.txt. 

@marchdf Are there any constraints on the sampler near domain boundaries. The bounds are [0,2560]X[0,2660]X[0,1280] and the plane goes until 2550 in X and Y and 1270 in Z but dx=dy=dz=20. You think this corner point can be an issue?

**Comment by marchdf** [comment]
missed that, thanks. Going to run it locally and see if I can figure that out.

**Comment by May0048** [comment]
Thank you. If you have time, please let me know the results of your operation, and I will adjust and try again.
---- Replied Message ----
| From | Marc T. Henry de ***@***.***> |
| Date | 10/15/2024 23:06 |
| To | Exawind/amr-wind ***@***.***> |
| Cc | May0048 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Exawind/amr-wind] An error occurred while running test (Issue #1292) |

missed that, thanks. Going to run it locally and see if I can figure that out.

**Comment by hgopalan** [comment]
If you do not need the corners you can reduce 2550 to 2500  and 1270 to 1200 and try. It should run without any issue.

**Comment by marchdf** [comment]
@May0048 I have fixes to those files in PR #1293. Those files should work now.

**Comment by marchdf** [comment]
@hgopalan it's not the high corners that are a problem, it's the low ones.

**Comment by marchdf** [comment]
Ok the fix I am happy with is in #1294

**Comment by May0048** [comment]
> Ok the fix I am happy with is in #1294

Thank you for your answer. I understand what you said. Now, if I use x, y = 0, 0 as the sampling origin, do I need to recompile AMR-Wind?

**Comment by moprak-nrel** [comment]
Since the fix involved changes to the code, I would update to the latest main branch and recompile AMRWind before you run your case again.

**Comment by May0048** [comment]
> Since the fix involved changes to the code, I would update to the latest main branch and recompile AMRWind before you run your case again.

Thank you for your reply. I understand what you mean,now.
