### ISSUE TITLE
Strange initialization for an offshore ABL simulation

### ISSUE THREAD

**Issue by rybchuk** [Exawind/amr-wind#1310]
## Bug description
I'm currently investigating if it's possible to run an offshore ABL simulation in inflow-outflow mode, like we do with land-based ABLs. As part of this work, I'm making some plots at time = 0 because I want to sanity check my understanding of these simulations. I'm seeing two strange things:
1. If I save an [xz-contour near the interface](https://github.com/user-attachments/assets/9a9bd578-2ff0-489b-be58-447b467dc190), the first half of the domain looks totally different than the second half of my domain. This is unexpected behavior. My domain is Lx = 2560 m, with `relax_zone_gen_length = 150.0` and `relax_zone_out_length = 600.0`.
2. If I [plot freesuface data](https://github.com/user-attachments/assets/37bac6c4-d3f1-460b-9545-553b0c9f3e55), two different unexpected things happen. First, the waves have an unexpectedly short wavelength. I'm running with `wave_length = 25.0`. Second, if I plot the freesurface variable at y = 80 m vs. y = 0 m, I end up with these regular patches of orange data where the saved out value is `-400`, which corresponds to `zlo`. My freesurface bounding box runs from `[-10, 10]` m, and my wave height is only 1.6 m.

## Steps to reproduce
Here is the input file, the static mesh refinement file, as well as my SLURM batch file. I'm able to run this simulation with 3 nodes on Kestrel. 

1. Compiler used
   - [ ] GCC
   - [ ] LLVM
   - [x] oneapi (Intel)
   - [ ] nvcc (NVIDIA)
   - [ ] rocm (AMD)
   - [ ] with MPI
   - [ ] other:
4. Operating system
   - [x] Linux
   - [ ] OSX
   - [ ] Windows
   - [ ] other (do tell ;)):
5. Hardware:
   - [x] CPU
   - [ ] GPU
6. Machine details ():
```
Currently Loaded Modules:
  1) intel/2023.2.0	  7) cray-libsci/23.12.5
  2) craype/2.7.30        8) PrgEnv-intel/8.5.0
  3) cray-dsmml/0.2.2     9) cray-python/3.11.5
  4) libfabric/1.15.2.0  10) binutils/2.41
  5) craype-network-ofi  11) intel-oneapi-compilers/2023.2.0
  6) cray-mpich/8.1.28
```
7. Input file attachments:
[offshore_initialization.zip](https://github.com/user-attachments/files/17481805/offshore_initialization.zip)

Also the notebook for

[1c_explore_freesurface.ipynb.zip](https://github.com/user-attachments/files/17481856/1c_explore_freesurface.ipynb.zip)
 analysis:

I've also dumped a bunch of things on Kestrel in `/scratch/orybchuk/share/offshore_init`.

8. Error (paste or attach):
See above. 

## Expected behavior
I expected the flow field to look similar in the region after the end of the wave spinup zone and before the numerical beach.

## AMR-Wind information
I'm seeing this behavior with two different versions of AMR-Wind: one version from October, and one from yesterday's code on `main`.
```
==============================================================================
                AMR-Wind (https://github.com/exawind/amr-wind)

  AMR-Wind version :: v3.1.5-17-gca437aff-DIRTY
  AMR-Wind Git SHA :: ca437affc6fd00490d8b14e244e53bf641207224-DIRTY
  AMReX version    :: 24.09-45-g6d9c25b989f1

  Exec. time	   :: Tue Oct 22 14:33:48 2024
  Build time	   :: Oct 21 2024 09:01:15
  C++ compiler     :: IntelLLVM 2023.2.0

  MPI              :: ON    (Num. ranks = 288)
  GPU              :: OFF
  OpenMP           :: OFF

  Enabled third-party libraries:
    NetCDF    4.9.2

           This software is released under the BSD 3-clause license.
 See https://github.com/Exawind/amr-wind/blob/development/LICENSE for details.
------------------------------------------------------------------------------
```

## Additional context
See above.

**Comment by mbkuhn** [comment]
![Screenshot 2024-10-22 at 4 03 46 PM](https://github.com/user-attachments/assets/ea16afe7-02bc-4c49-897a-567572d98cf2)

![Screenshot 2024-10-22 at 4 05 26 PM](https://github.com/user-attachments/assets/6dee3709-8684-4496-be57-1265bb7b4282)

I don't have anything to say yet about the second issue, but regarding the first one: The boundary of the refinement zones is the difference between the two halves. The height of the waves is much smaller than the cell size in the coarse part of the mesh. That's why it looks so weird when you look at a slice; it becomes underresolved quickly.

**Comment by mbkuhn** [comment]
However, the "interface location" is still following basically the same profile, though it's hard to see:
![Screenshot 2024-10-22 at 4 10 36 PM](https://github.com/user-attachments/assets/2fc8b618-d44c-4de9-899e-bf433eec6244)

**Comment by mbkuhn** [comment]
BTW, I am really excited that you're venturing into this! There are a couple things you'll want to tweak in your input file for the actual run. But I will try to figure out what's going on with the freesurface sampler, which should be unrelated to those other things.

**Comment by mbkuhn** [comment]
when the freesurface sampler can't find the interface, it outputs the bottom of the domain. It's wrong to not be able to find the interface, but that's where the -400 comes from.

**Comment by rybchuk** [comment]
Oh my gosh //facepalm, sorry about the mesh refinement miss. Thanks for catching that! And yeah I'm excited to finally have time to dig into offshore ABL simulations again :)

**Comment by mbkuhn** [comment]
the freesurface weirdness, namely the "short wavelength": does it occur over the whole region in x? does it look any different in the coarser part of the domain?

Could you see if the problem goes away if you use this AMR-Wind commit? 
89eacad
If it does, could you see if the problem occurs with this commit?
f336699

**Comment by rybchuk** [comment]
Using commit 89eacad,
1. If I keep `static_box.txt` like I had it before (with the 1280 m refinement zone), the -400 gaps [still show up at y=80 m](https://github.com/user-attachments/assets/1287e513-01dd-4b65-8c56-d2f0a9b10e4f)
2. If I correct `static_box.txt` to have a refinement zone over the entirety of Lx, the -400 gaps [disappear at y=80 m](https://github.com/user-attachments/assets/840e4434-da67-4a5e-bb9e-359b2882bcd5)

In both of these scenarios, the freesurface is still showing a short wavelength.
* Here's a visual comparison of freesurface and a VoF cross-section using the old `static_box.txt` simulation in the region with the refinement zones ([1](https://github.com/user-attachments/assets/2fce8342-f6b6-43e2-a088-9480ca5d891c), [2](https://github.com/user-attachments/assets/4dd26605-a6a9-4494-b22b-64a9491422da)) and the region without the refinement zones ([1](https://github.com/user-attachments/assets/cf58fd12-88f1-4454-b4c2-bc273919a714), [2](https://github.com/user-attachments/assets/826f1646-b67b-4507-b96d-a221c9a0de9e)).

**Comment by rybchuk** [comment]
I just did a quick sanity check to make sure that I'm reformatting the freesurface data correctly into a 2-d array, and I am indeed. 
* Here's what the freesurface data looks like in the `static_box.txt` = 1280 m simulations in the [refined region](https://github.com/user-attachments/assets/23ab3e3b-3a58-4065-bb9b-ec4d64241bc0) and the [unrefined region](https://github.com/user-attachments/assets/7728d0b8-fcc8-4c52-8aed-40fa7082d5df). 
* Here's [the same](https://github.com/user-attachments/assets/83ca1a3b-d66c-4117-828e-8e92f0f1090e) for the `static_box.txt` = 2560 m simulations

The 2560 m plots suggest that the waves at t0 aren't being initialized with a 25 m wavelength. There's a shorter wavelength on the order of 2 m and also a longer wavelength on the order of 20 m. I'm also surprised that the waves are being initialized at an angle instead of parallel to the y-axis. I wonder if this has something to do with my specific prescribed wavelength of 25 m or the fact that domain Lx != domain Ly.
* Here's that [top-down view](https://github.com/user-attachments/assets/a5b378ac-3dfc-4401-8ebe-a69a144fb91a) using a prescribed wavelength of 100 m instead
* Here's a [top-down view](https://github.com/user-attachments/assets/3d7a8d6e-c09e-4c6b-a7fc-8bdcb0a58350) if I use a wavelength of 25 m and Lx = Ly = 1280 m. I'm uncertain why we're getting gaps in this one. The static box also spans 1280 m in this simulation.

The diagonal wave thing is confusing me. Funny enough, I was DM'ing you on Teams in mid-September, and I sent you a top-down view of freesurface data after a spinup of 10 min, and the waves are not diagonal... though they are parallel to the x-axis instead of the y-axis?

**Comment by mbkuhn** [comment]
![Screenshot 2024-10-23 at 3 43 36 PM](https://github.com/user-attachments/assets/0d93ba9f-2048-4a80-889b-3bf19f64b0e0)

Looking at the wave elevation in paraview, the waves aren't actually diagonal. This has to be due to either the free surface sampler, the post-processing routine, or a mismatch in expectations between the two.

**Comment by mbkuhn** [comment]
for there to be those random -400 values, there is likely something wrong with the sampler. But the diagonal-ness may be a flaw in the setup of the post-processing script, or at least its expectations of what is coming from AMR-Wind. I'll take a look.

**Comment by rybchuk** [comment]
Oof, it looks like all the remaining issues stem from my post-processing code. My `np.reshape` operation wasn't putting wave heights in the correct location, which lead to a diagonal issue. 

I updated my code (attached), and the waves look good now ([1](https://github.com/user-attachments/assets/ceace212-b572-45a4-8376-6ca4dfe54ced),[2](https://github.com/user-attachments/assets/b0b65294-03f4-40ff-b641-a97fb830bbe1)). I couldn't find any -400 values either in the simulations that have `static_box.txt` specified correctly, though maybe some -400 values are hiding around the perimeter. 


 
[1c_explore_freesurface_corrected.ipynb.zip](https://github.com/user-attachments/files/17509107/1c_explore_freesurface_corrected.ipynb.zip)
