### ISSUE TITLE
No plt files written, even though chk files are? 

### ISSUE THREAD

**Issue by ndevelder** [Exawind/amr-wind#1314]
I'm running a hybrid solver and requesting the below output in AMR-Wind, but the plt files are not being written out, while the chk files are. Haven't dug into code yet, just posting in case someone has any quick solutions/ideas. 

time.stop_time                           = -1.0                # Max (simulated) time to evolve [s]
time.max_step                            = -1                  
time.fixed_dt                            = 0.003443526170799   # Fixed timestep size (in seconds). If negative, then time.cfl is used
time.plot_interval                       = 2000  
time.checkpoint_interval                 = 4000                  
incflo.physics                           = ABL                 # List of physics models to include in simulation.
incflo.verbose                           = 0                   
io.plot_file                             = out01/plt
io.check_file                            = rst01/chk   

**AMR-Wind versions here:**

AMReX (24.09-45-g6d9c25b989f1) initialized
                AMR-Wind (https://github.com/exawind/amr-wind)

  AMR-Wind version :: v3.1.5-17-gca437aff
  AMR-Wind Git SHA :: ca437affc6fd00490d8b14e244e53bf641207224
  AMReX version    :: 24.09-45-g6d9c25b989f1

  Exec. time       :: Thu Oct 24 00:34:36 2024
  Build time       :: Oct 16 2024 22:19:30
  C++ compiler     :: Intel 2021.10.0.20230609

  MPI              :: ON    (Num. ranks = 6496)
  GPU              :: OFF
  OpenMP           :: OFF

  Enabled third-party libraries: 
    NetCDF    4.9.2
    HYPRE     2.31.0

This software is released under the BSD 3-clause license.           
See https://github.com/Exawind/amr-wind/blob/development/LICENSE for details.

**Comment by mbkuhn** [comment]
this is probably a dumb question to ask, but is there any "time.plot_delay" or "time.plot_time_delay" argument in your input file? Or "time.plot_time_interval"?

**Comment by ndevelder** [comment]
Thanks Mike! Yep, this was dumb...but also confusing. There is a 

time.plot_start                          = 30000    

But technically AMR-Wind is restarting with precursor input at timestep 30000, so maybe this is ok? 

And someone had stuck this in the ABL section, so technically there are 2 calls to this flag, so it must be picking up the second one in place of the first? 

time.plot_interval                       = -1     

I might try and add a duplicate flag checker at some point...

**Comment by marchdf** [comment]
`time.plot_interval = -1` turns off plot file output. And yeah it always takes the last entry (CLI has the highest precedence).

**Comment by mbkuhn** [comment]
oh, yeah. it will pick the second over the first. That is the reason why they aren't being output.

the plot_start might not be necessary, but I don't think it's causing any problems. As I understand it, plot_start helps when your precursor data starts at a timestep that's not a multiple of your plot interval.

**Comment by marchdf** [comment]
Sounds like we can close this?
