### ISSUE TITLE
Forest Canopy Model

### ISSUE THREAD

**Issue by hgopalan** [Exawind/amr-wind#1322]
Forested region affects the incoming ABL profile and also affects the structural loads on turbines (https://onlinelibrary.wiley.com/doi/pdf/10.1002/we.2076). Adding a forest canopy models will provide us the ability to study these effects using AMR-Wind + ALM or AMR-Wind + FAST.Farm. I am planning to add a forest canopy model capability in AMR-Wind. If there are any specific feature-requests, please provide them in this thread.

**Comment by hamidMech** [comment]
Hello, thank you for considering the forest modeling feature in AMR-Wind. Here is some information that may be helpful for implementing this feature in AMR-Wind.
Forest canopies may be modeled as either homogeneous or heterogeneous, with both being considered as drag forces influencing ABL flow. For horizontally homogeneous forest canopies, modeling is provided using Leaf Area Density (LAD) or Plant Area Density (PAD), varied only in the vertical direction. These simplified models are treated as uniform drag, affecting flow characteristics within the ABL. However, to reduce uncertainties of homogeneous modeling, heterogeneous canopy modeling may also be introduced. In this approach, Plant Area Index (PAI) or Leaf Area Index (LAI) profiles are varied both horizontally and vertically. This inhomogeneous representation is considered critical for accurately capturing wind field variability, particularly in wind farms located in complex terrains. Finally, previous research have shown that assuming a homogeneous forest can lead to an overestimation of turbulence intensity when compared to a more realistic heterogeneous forest model. 
Best regards,
Hamid

**Comment by hgopalan** [comment]
It will be a vertically heterogeneous forest model using the empirical LAD description from https://journals.ametsoc.org/view/journals/apme/43/4/1520-0450_2004_043_0641_aerdld_2.0.co_2.xml?tab_body=pdf

**Comment by hamidMech** [comment]
In heterogeneous forest modeling, the vertical and horizontal distribution of Leaf Area Density (LAD) or Plant Area Density (PAD) may be represented using a table with columns labeled "x," "y," "z," and "PAD". This format treats PAD as a function of spatial coordinates, allowing for a comprehensive representation of the distribution across both vertical ("z") and horizontal dimensions. Specifically, when using LAS (LIDAR Aerial Survey) data, PAD is derived to accurately reflect the characteristics of forest canopies.

In contrast, homogeneous forest modeling often assumes that PAD/LAD is uniformly distributed across the horizontal plane ("xy" plane) and only varies vertically along the "z" axis, represented through a PAD/LAD profile. This simplified approach focuses exclusively on vertical variation, disregarding any horizontal differences.

**Comment by hgopalan** [comment]
Currently, I do not plan to include horizontal heterogeneity unless there is a real need in the future to have the capabilities. The amount of work involved and book keeping is too much. The aim of this model is to provide capabilities similar to other vertically heterogeneous forest profiles available in other codes for LES/RANS modeling.
