### ISSUE TITLE
FOWT simulations in AMR-Wind

### ISSUE THREAD

**Issue by delloiacono** [Exawind/amr-wind#1327]
Hi,

what are the capabilities of AMR-Wind (also coupled with OpenFAST) for simulation of floating offshore wind turbines? Is there anything already developed or ongoing?

Thanks in advance.

**Comment by hgopalan** [comment]
What kind of capabilities are you looking for? There are some features available and some are in development.

**Comment by delloiacono** [comment]
Primarily I am looking at how to simulate the turbine base platform:
- The geometry of the platform is represented with some method (e.g. IB) or with just a point that denotes the position of the base?
- How can the platform motion be set?

Can you also indicate some other features available or coming soon?

**Comment by hgopalan** [comment]
@mbkuhn Can you advise?

**Comment by michaelasprague** [comment]
@delloiacono -- thanks for the question.  Floating offshore wind is a work in progress.  We have two-phase flow capabilities in both AMR-Wind and Nalu-Wind and we have done preliminary validation of wave loading on a fixed body.  Now through 2025, we will be doing verification and validation simulations of fixed and floating bodies where the near-body fluid is simulated with Nalu-Wind and the off-body fluid will be solved with AMR-Wind.   We are also implementing a 6-DOF rigid-body solver in OpenTurbine, which will be coupled to Nalu-Wind.

**Comment by CaiZhiming-HHU** [comment]
@delloiacono 

Hello!
 would suggest utilizing the floating platform and hydrodynamic modules in OpenFAST to perform fluid-structure interaction (FSI) simulations for floating wind turbines. Although the hydrodynamic loads on the platform are not rigorously coupled fluid dynamics (but rather based on potential flow theory solutions pre-computed by tools like WAMIT or AQWA), this approach should meet your requirements. The attached figure demonstrates results from my simulation of the NREL 5-MW reference turbine mounted on an OC4 Phase II floating platform using the aforementioned methodology.

![Image](https://github.com/user-attachments/assets/2e8e11a6-5d58-41fa-b3ac-8546c76a2148)
