### ISSUE TITLE
Offshore boundary plane failing time tolerance

### ISSUE THREAD

**Issue by rybchuk** [Exawind/amr-wind#1342]
## Bug description
Likely related to [this PR](https://github.com/Exawind/amr-wind/pull/1329), and I am using the most recent commit on `main`, `740679c8`. I'm running an offshore ABL simulation with linear waves. I have achieved a spun-up state at iteration `80000`, and now I am trying to run an inflow-outflow simulation. I believe that I have successfully written out boundary planes using the following:
```
ABL.bndry_file                           = bndry_file.native
ABL.bndry_io_mode                        = 0
ABL.bndry_planes                         = ylo xlo
ABL.bndry_output_start_time              = 1.0
ABL.bndry_var_names                      = velocity_mueff velocity density p velocity_src_term gp vof_mueff levelset interface_curvature vof vof_src_term temperature_mueff temperature temperature_src_term ow_levelset ow_vof ow_velocity
```
(I know that I'm probably saving out too many boundary variables, but I saw the same error with `= velocity temperature vof`)

I then kick off the inflow-outflow simulation using the following variables:
```
ABL.bndry_file                           = ../write_lev0/bndry_file.native
ABL.bndry_io_mode                        = 1
ABL.bndry_planes                         = ylo xlo
ABL.bndry_output_start_time              = 1.0
ABL.bndry_var_names                      = velocity_mueff velocity density p velocity_src_term gp vof_mueff levelset interface_curvature vof vof_src_term temperature_mueff temperature temperature_src_term ow_levelset ow_vof ow_velocity # velocity temperature vof
```

The simulation errors out during the first timestep.

## Steps to reproduce
I have shared all the files needed to run the bc-write simulation and bc-read simulation in `/scratch/orybchuk/share/debug_inflow_outflow` on Kestrel. I've uploaded many of the files (aside from the large ones) here too.

[debug_inflow_outflow.zip](https://github.com/user-attachments/files/17706790/debug_inflow_outflow.zip)

1. Compiler used
   - Oneapi
2. Operating system
   - Linux
3. Hardware:
   - CPU
4. Machine details ():
Kestrel
```
Currently Loaded Modules:
  1) intel/2023.2.0	  7) cray-libsci/22.10.1.2
  2) craype/2.7.30        8) PrgEnv-intel/8.5.0
  3) cray-dsmml/0.2.2     9) cray-python/3.11.5
  4) libfabric/1.15.2.0  10) binutils/2.41
  5) craype-network-ofi  11) intel-oneapi-compilers/2023.2.0
  6) cray-mpich/8.1.28
```
5. Input file attachments: See the `.zip` file.
6. Error (paste or attach):
```
==============================================================================
Step: 80011 dt: 0.05 Time: 6542.942863 to 6542.992863
CFL: 0.402303 (conv: 0.402303 diff: 0 src: 0 )

Godunov:
  System                     Iters      Initial residual        Final residual
  ----------------------------------------------------------------------------
terminate called after throwing an instance of 'std::runtime_error'
...
  what():  Assertion `std::abs(time - m_in_data.tinterp()) < 1e-12' failed, file "/kfs2/projects/ai4wind/orybchuk/exawind-manager/environments/ai4wind-nov24/amr-wind/amr-wind/wind_energy/ABLBoundaryPlane.cpp", line 896
```
7. If this is a segfault, a stack trace from a debug build (paste or attach):
N/A

## Expected behavior
The bc-read simulation should run past the first timestamp without crashing.

## AMR-Wind information

```
==============================================================================
                AMR-Wind (https://github.com/exawind/amr-wind)

  AMR-Wind version :: v3.2.0-8-g740679c8-DIRTY
  AMR-Wind Git SHA :: 740679c87925db41521f477e8724daa0c69cc670-DIRTY
  AMReX version    :: 24.09-45-g6d9c25b989f1

  Exec. time	   :: Mon Nov 11 10:48:20 2024
  Build time	   :: Nov 11 2024 10:17:52
  C++ compiler     :: IntelLLVM 2023.2.0

  MPI              :: ON    (Num. ranks = 384)
  GPU              :: OFF
  OpenMP           :: OFF

  Enabled third-party libraries:
    NetCDF    4.9.2

           This software is released under the BSD 3-clause license.
 See https://github.com/Exawind/amr-wind/blob/development/LICENSE for details.
------------------------------------------------------------------------------
```

## Additional context
I tried initializing the bc-read simulation from `chk80000` and `chk80010`, and it fails for both checkpoints.

For the record, the timing of `chk80010` looks like `Step: 80011 dt: 0.05 Time: 6542.942863 to 6542.992863`, and the first few timestamps of the BC are:
```
80000 6542.4428627258721
80001 6542.5721400248704
80002 6542.6563112443018
```
so the BC definitely has data before the IC. The precursor simulation was run with an adaptive timestamp, but the bc-write and bc-read simulations are currently being run with a small fixed timestamp. I was also hitting the same error with a version of AMR-Wind that I compiled from `main` in October.

**Comment by rybchuk** [comment]
I did some more investigating, but have not been able to figure out a quick fix. I changed the time tolerance from `1e-12` to the aggressive `1e-4`, and that didn't work. 
```
  what():  Assertion `std::abs(time - m_in_data.tinterp()) < 1e-4' failed, file "/kfs2/projects/ai4wind/orybchuk/exawind-manager/environments/ai4wind-nov24/amr-wind/amr-wind/wind_energy/ABLBoundaryPlane.cpp", line 900
```

I also added some print statements into `ABLBoundaryPlane.cpp` to see the values of everything:
```
    amrex::Print() << "time: " << time << std::endl;
    amrex::Print() << "m_in_data.tn(): " << m_in_data.tn() << std::endl;
    amrex::Print() << "m_in_data.tnp1(): " << m_in_data.tnp1() << std::endl;
    amrex::Print() << "m_in_data.tinterp(): " << m_in_data.tinterp() << std::endl;
    AMREX_ALWAYS_ASSERT(
        ((m_in_data.tn() <= time) || (time <= m_in_data.tnp1())));
    AMREX_ALWAYS_ASSERT(std::abs(time - m_in_data.tinterp()) < 1e-6);
```

Surprisingly, the values of `time` and `m_in_data.tinterp()` are printed out as identical:
```
time: 6542.942863
m_in_data.tn(): -1
m_in_data.tnp1(): -1
m_in_data.tinterp(): 6542.942863
```

I assume that `m_in_data.tn()` and `m_in_data.tnp1()` are supposed to be `-1`?

**Comment by mbkuhn** [comment]
I'm confident I found the problem. The time passed to a vof fillpatch (within the advection step) is not valid, leading to a problem with this assertion. I'm not sure what the best solution is, but to confirm this is the problem, you could try running without vof as one of the bndry variables. This would also explain why this problem is showing up for offshore ABLs in particular.

**Comment by rybchuk** [comment]
Yep, I can confirm! If I run with my code that was compiled back in October and I set `ABL.bndry_var_names = velocity temperature`, the code makes it through the first few timesteps without any errors.

**Comment by mbkuhn** [comment]
Putting these here for myself and other developers:
https://github.com/Exawind/amr-wind/blob/main/amr-wind/equation_systems/vof/SplitAdvection.cpp#L102
https://github.com/Exawind/amr-wind/blob/main/amr-wind/equation_systems/vof/vof_ops.H#L73

both of these would lead to breaking the assertion. The second one is easy to fix. The first one is a problem for two reasons:
1. easier issue - need to pass in the time to SplitAdvection so it can have a valid value.
2. harder issue - vof boundaries need to be at n, not n+1/2, defying the new way I set up the boundary fill times. Probably will need some type of specific exception to leave the boundaries at n while still doing fillpatch stuff elsewhere, kind of like what I did for the sibling fields fill.

**Comment by mbkuhn** [comment]
When you get a chance, could you also check with the more recent code, and just taking vof out of the input bndry variable names? No hurry

**Comment by rybchuk** [comment]
It's a quick thing for me to check :) I un-uncommented the `AMREX_ALWAYS_ASSERT` with yesterday's code, and I can confirm that that also runs through the first few timestamps without issue.

**Comment by hgopalan** [comment]
Adding to our previous discussion, I randomly get a code crash at : 

    AMREX_ALWAYS_ASSERT(
        ((m_in_data.tn() <= time) || (time <= m_in_data.tnp1())));

It happens on both CPUs and GPUs. I would say 10% of my cases see this issue.

**Comment by rybchuk** [comment]
So... when I submitted the issue, I unfortunately set up my inflow-outflow simulation incorrectly. While I set `ABL.bndry_io_mode = 1`, I was also running `geometry.is_periodic = 1   1   0`. As a result, it's ambiguous if I was accidentally running my inflow-outflow simulation as a periodic simulation.

I'm now trying to run the inflow-outflow simulation with:
```
ABL.bndry_io_mode                        = 1
ABL.bndry_planes                         = xlo
...
geometry.is_periodic                     = 0   1   0

xlo.type                                 = mass_inflow
xlo.density                              = 1.027
xlo.temperature                          = 265.0
xlo.tke                                  = 0.0
xhi.type                                 = pressure_outflow
```

The simulation now errors out with
```
AMReX (24.09-45-g6d9c25b989f1) initialized
Initializing AMR-Wind ...
ParmParse::sgetarr ParmParse::sgetarr(): xlo.vof not found in table
```

This error is being reported by `amrex/Src/Base/AMReX_ParmParse.cpp`. Do you have any suggestions on what to do about `xlo.vof`? I don't see any examples of this line in the repo. Also, what should I do about `xlo.density` when `MultiPhase` expects two densities?

**Comment by rybchuk** [comment]
Harish suggested setting `xlo.vof = 0` (where 0 is a dummy value), and my simulation is now running again :) I hope to have results soon with a longer inflow-outflow simulation

**Comment by mbkuhn** [comment]
Thanks, @hgopalan, that's a great suggestion for this scenario

**Comment by rybchuk** [comment]
I ran the simulation out for 200 iterations (10 seconds). Based off the [vof field](https://github.com/user-attachments/assets/5a2b918f-380b-4f68-8fdb-3f7525c55778) by the end of the simulation, the numerical beach is indeed damping the waves. Here's [pressure](https://github.com/user-attachments/assets/b47a5a90-1506-4156-82fe-a81ccff3a565) at that last step too.

Unfortunately, [u](https://github.com/user-attachments/assets/391bf839-9c80-42ed-b9ae-bfe290388246), [v](https://github.com/user-attachments/assets/aef63c8f-0f8e-46da-a0c6-121b8bd903c7), [w](https://github.com/user-attachments/assets/2f1fd334-f446-4154-ad5f-f8a61b58c44e), and [T](https://github.com/user-attachments/assets/6193ebbc-5d90-4f38-a17d-b55900022d70) look funny at the outflow. This feels like I botched something with the inflow-outflow `.i` file though. I haven't run inflow-outflow simulations in a bit, so let me confirm that I remember how to properly run them on land.

**Comment by mbkuhn** [comment]
are you using ABL Mean Boussinesq in there too?

**Comment by rybchuk** [comment]
Nope, good catch.

I've added ABL Mean Boussinesq in there. I've also run the `calc_inflow_stats.py` script but commented out all the `ABL` lines because these values feel like they're specific to land-based ABLs with Monin-Obukhov.
```
ICNS.source_terms                        = BoussinesqBuoyancy CoriolisForcing GeostrophicForcing GravityForcing ABLMeanBoussinesq
##--------- Additions by calc_inflow_stats.py ---------#
# ABL.wall_shear_stress_type = "local"
# ABL.inflow_outflow_mode = true
# ABL.wf_velocity = -0.04061319424974897 0.01560499433783477
# ABL.wf_vmag = 0.05284818547325939
# ABL.wf_theta = 265.0000040814566
# BodyForce.magnitude = 0.0 0.0 0.0
BoussinesqBuoyancy.read_temperature_profile = true
BoussinesqBuoyancy.tprofile_filename = avg_theta.dat
##-----------------------------------------------------#
```

After making that change, my inflow-outflow simulation ran for the full requested two minutes without any obvious issues ([u](https://github.com/user-attachments/assets/c1f1c3d2-ccc7-40d1-b4c8-1da4a17d2f64), [v](https://github.com/user-attachments/assets/07a9aa70-6f97-40ef-8d64-b5aff7ed9963), [w](https://github.com/user-attachments/assets/68f8454d-c58e-41dd-8dc3-c7c67f16e08a), [T](https://github.com/user-attachments/assets/f82b97f5-c2ea-4648-8e1c-2ac7022dc579))!

Whereas the above simulations didn't have any refinement zones, I also ran ~20 seconds of an inflow-outflow simulation with two levels of refinement. The [u](https://github.com/user-attachments/assets/70b69d8d-b1d8-4076-80f9-5b3794fbd11e), [v](https://github.com/user-attachments/assets/38a30ba4-5d67-4450-8788-c475a8ff5bbc), [w](https://github.com/user-attachments/assets/e9b05a6f-b8cb-455e-be81-0d6072923ca8), and [T](https://github.com/user-attachments/assets/4dfe699e-31ed-4ba6-9860-ac6a6b79afea) fields also look good there!

I've attached the read and write `.i` files below for reference for posterity.
[offshore_io.zip](https://github.com/user-attachments/files/17903959/offshore_io.zip)

-----

I'm going to do some more futzing around now, where I take BCs from a spun-up simulation and I try to drive a simulation with quiescent ICs, but that's not relevant to this issue. The VoF fillpatch workaround that I've been using looks like it works great for the time being, so there's no pressing need from me to thinking about the VoF fillpatch code more rigorously. Thanks for the help!

**Comment by marchdf** [comment]
That's awesome news @rybchuk . Good to close the issue then?

**Comment by mbkuhn** [comment]
@rybchuk, do you think you could try out the above pull request to see if it passes the asserts when you include vof as a boundary variable?
