### ISSUE TITLE
`native` output format sampling only saves one group

### ISSUE THREAD

**Issue by rthedin** [Exawind/amr-wind#1383]
## Bug description
I switched to the `native` output format given extensive conversations about performance of `netcdf` and noticed it only saved a single group/label (appears to be the first one). I believe this is not the expected behavior.

## Steps to reproduce

1. Compiler used
   - [x] oneapi (Intel)
2. Operating system
   - [x] Linux
3. Hardware:
   - [x] CPU
4. Machine details ():
Kestrel

5. Input file attachments
Can provide a path on Kestrel for a test case if need be

6. Error (paste or attach):
Only one group appears to be available when using the [`amrex_particle`](https://github.com/Exawind/amr-wind/blob/v3.2.0/tools/amrex_particle.py) reader

## Expected behavior
I would expect all groups to be saved, maybe in separate directories. I know netcdf has the groups option which is convenient, but it appears like the `native` is lacking the ability to request multiple labels.

## AMR-Wind information

```
==============================================================================
                AMR-Wind (https://github.com/exawind/amr-wind)

  AMR-Wind version :: v3.2.0
  AMR-Wind Git SHA :: bb0e9dcc59c694812a03703199ade0a3984161d5
  AMReX version    :: 24.09-45-g6d9c25b989f1

  Exec. time       :: Tue Dec  3 11:19:57 2024
  Build time       :: Nov 18 2024 15:10:15
  C++ compiler     :: IntelLLVM 2023.2.0

  MPI              :: ON    (Num. ranks = 64)
  GPU              :: OFF
  OpenMP           :: OFF

  Enabled third-party libraries:
    NetCDF    4.9.2
    OpenFAST

           This software is released under the BSD 3-clause license.
 See https://github.com/Exawind/amr-wind/blob/development/LICENSE for details.
------------------------------------------------------------------------------
```

**Comment by rybchuk** [comment]
I saw something similar a few weeks back. I ran two simulations where I was saving ~20 offset xz planes. One simulation wrote out in netCDF, the other in native. The saved out `.nc` file was ~20x larger than the data from the native simulation. I also opened up the native data using [amrex_particle.py](https://github.com/Exawind/amr-wind/blob/main/tools/amrex_particle.py) and I couldn't find the data from the offset planes (though I didn't spend much time on this).

**Comment by rthedin** [comment]
In my cases I am seeing the offsets just fine. At the end of the day, the data is flattened the same way as the netcdf. I was just not able to see the groups/labels. I didn't pay attention to the file size-- that's a good sign that the two methods are different.

**Comment by rybchuk** [comment]
Oh woah, okay that's useful to hear. Based off this comment to myself, I definitely saw an offset bug

![image](https://github.com/user-attachments/assets/23a14ac8-44ea-4854-9aee-0409904d83fc)

As a note: I'm sticking with netCDF sampling for the time being, so this bug doesn't affect me.

**Comment by marchdf** [comment]
@rthedin I am a bit confused. Would you mind sharing your input file? I checked all this with that large sampling case you initially shared with me and everything looked fine?

**Comment by rthedin** [comment]
Sure thing. See attached. 
[samplingexample.i.txt](https://github.com/user-attachments/files/18011684/samplingexample.i.txt)

The main point from the example file is that there are two labels on the group `box_hr`:
```
box_hr.labels           = HighT1_inflow0deg HighT2_inflow0deg
```
And I am not able to see both being saved.

**Comment by marchdf** [comment]
hmmm so they should be part of the same particle file. For example, using `abl_sampling.inp` regression test file, we have `plane_sampling.labels  = plane1 plane2`. If I open `plane_sampling*` in paraview, and viz the `set_id` value, then I see particles labelled 0 and 1, which correspond to the strings in the `labels` input (see pic). Yes, these aren't the actual strings the user set but we can't output strings as particle data. And for efficiency, they are part of the same particle container.

<img width="1507" alt="Screenshot 2024-12-04 at 10 06 12 AM" src="https://github.com/user-attachments/assets/c5f64a33-38c5-4968-9a70-834a6854b272">

Would you mind checking your particle data to see if you see a similar `set_id` that corresponds to the different labels?

Now as to why `amrex_particle.py` isn't reading this right, that's my next order of business.

**Comment by marchdf** [comment]
Ok and (at least for this reg test), I see:
```
❯ python3 /Users/mhenryde/exawind/source/amr-wind/tools/fcompare_particles.py post_processing/plane_sampling00000 post_processing/plane_sampling00000
     uid  set_id  probe_id          xco     yco    zco  velocityx  velocityy  velocityz
0      0       0         0   200.000000   200.0  200.0   6.129077   5.143022        0.0
1      1       0         1   244.444444   200.0  200.0   6.129077   5.144596        0.0
2      2       0         2   288.888889   200.0  200.0   6.129077   5.143590        0.0
3      3       0         3   333.333333   200.0  200.0   6.129077   5.141153        0.0
4      4       0         4   377.777778   200.0  200.0   6.129077   5.140006        0.0
..   ...     ...       ...          ...     ...    ...        ...        ...        ...
595  595       1       195   555.555556  1000.0  999.0   6.128356   5.142301        0.0
596  596       1       196   666.666667  1000.0  999.0   6.128356   5.142301        0.0
597  597       1       197   777.777778  1000.0  999.0   6.128356   5.142301        0.0
598  598       1       198   888.888889  1000.0  999.0   6.128356   5.142301        0.0
599  599       1       199  1000.000000  1000.0  999.0   6.128356   5.142301        0.0

[600 rows x 9 columns]
````

Which is right because adding both planes is 600 particles:
```
plane_sampling.plane1.num_points    = 10 10
plane_sampling.plane1.offsets       = 0.0 20.0 30.0 200.0
...
plane_sampling.plane2.num_points    = 10 10
plane_sampling.plane2.offsets       = 0.0 499.0
```

So now I am confused as to why this is working for this case and not for yours...

**Comment by rthedin** [comment]
Ah, okay, I can see both groups now. I was not aware `set_id` referred to groups/labels and I wasn't considering it in my processing. But it makes sense now. Is the order of the `set_id`s the same as the order passed on to the `*.labels` entry on the input file? I understand you can't have a string-- and that's okay-- but just checking on the order.

**Comment by marchdf** [comment]
Yup order should be the same. So all good then for this issue? No need for me to run your case? I am going to add a bit of documentation so you can leave this open until then.

@rybchuk I am not sure what issue you were having but it seems different? Or the same?

**Comment by marchdf** [comment]
Ran your case anyway... I see
```
           uid  set_id  probe_id      xco     yco     zco  velocityx  velocityy  velocityz
0            0       0         0   531.25  471.25    1.25   7.994045  -0.004760        0.0
1            1       0         1   536.25  471.25    1.25   7.994045  -0.005102        0.0
2            2       0         2   541.25  471.25    1.25   7.994045  -0.005393        0.0
3            3       0         3   546.25  471.25    1.25   7.994045  -0.005666        0.0
4            4       0         4   551.25  471.25    1.25   7.994045  -0.005883        0.0
...        ...     ...       ...      ...     ...     ...        ...        ...        ...
618925  618925       1    309460  2531.25  811.25  321.25   7.829390  -0.152258        0.0
618926  618926       1    309461  2536.25  811.25  321.25   7.829390  -0.143906        0.0
618927  618927       1    309462  2541.25  811.25  321.25   7.829390  -0.134088        0.0
618928  618928       1    309463  2546.25  811.25  321.25   7.829390  -0.123846        0.0
618929  618929       1    309464  2551.25  811.25  321.25   7.829390  -0.112335        0.0

[618930 rows x 9 columns]
```
And that adds up to the number of particles I would expect 69*69*65*2

**Comment by rthedin** [comment]
Yup, all good. There was no need to run my case but I appreciate you running it. Thanks for the clarification, Marc.
