### ISSUE TITLE
Assertion `info.root_proc > -1' failed

### ISSUE THREAD

**Issue by marchdf** [Exawind/amr-wind#1385]
## Bug description
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Assertion `info.root_proc > -1' failed, file "/autofs/nccs-svm1_home1/marchdf/exawind/exawind-manager/environments/amr-wind-of/amr-wind/amr-wind/wind_energy/actuator/turbine/fast/turbine_fast_ops.H", line 186
```

This is due to something I did in #1360: specifically, calling `post_regrid_actions`  on L81 of `incflo.cpp`.  `Actuator::post_regrid_actions()` is doing something different than the others and doesn't have the information it would like...

**Comment by marchdf** [comment]
I think what's going on is:

`Actuator::post_regrid_actions()` calls `act->determine_influenced_procs()`

and that is in `turbine_fast_ops.H` which has a check for `AMREX_ALWAYS_ASSERT(info.root_proc > -1)` but `act->determine_root_proc(act_proc_count)` hasn't been called yet because `post_init_actions` hasn't been called yet.

So is the fix to have a `determine_root_proc` call in `post_regrid_actions`?

**Comment by mbkuhn** [comment]
Is it possible to determine the root proc in pre_init_actions?

**Comment by marchdf** [comment]
yes maybe... going to try that.

**Comment by May0048** [comment]
Hello, I encountered the same error mentioned above when running the example of three wind turbines, do you know what caused it?

<img width="363" alt="Image" src="https://github.com/user-attachments/assets/412748d1-07df-4bf2-b6f3-b18f6dd12343" />

<img width="393" alt="Image" src="https://github.com/user-attachments/assets/3e313148-75d6-46f2-9519-e4d5950b4fb7" />
