### ISSUE TITLE
The "Header" file cannot be opened

### ISSUE THREAD

**Issue by May0048** [Exawind/amr-wind#1386]
When I was running according to the drill in the guidance manual, the following error occurred in the simulation of the precursor, showing that the "Header" file could not be opened, I am sure that this file exists in the path I wrote, the following is my input file, hope you can answer, thank you.
[pre.txt](https://github.com/user-attachments/files/18024184/pre.txt)
![a0eded45802613055288b57b6733eec](https://github.com/user-attachments/assets/dc657690-fc4b-4b98-94c0-7bb21460827f)

**Comment by May0048** [comment]
> Can you attach the output of `ls -R ../spinup./*` from your run directory?

This is the spinup file generated by the previous simulation. Is there something wrong with the file I generated earlier?
![bdaf8fc9837758192e5a5fadaca97c3](https://github.com/user-attachments/assets/54e8814e-0887-470f-8db2-1437477c5396)
![fa7683e5367af0831f53a37b0ed21e3](https://github.com/user-attachments/assets/3085bab3-5442-4fc2-a2f0-cf78e0ad3b69)

**Comment by marchdf** [comment]
That looks fine... Is this a windows machine?

**Comment by May0048** [comment]
Yes, I use the Ubuntu for computation.
---- Replied Message ----
| From | Marc T. Henry de ***@***.***> |
| Date | 12/06/2024 02:01 |
| To | Exawind/amr-wind ***@***.***> |
| Cc | May0048 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Exawind/amr-wind] The "Header" file cannot be opened (Issue #1386) |

That looks fine... Is this a windows machine?

**Comment by marchdf** [comment]
Are you _sure_ you have the relative paths right?

**Comment by May0048** [comment]
Sorry, I made a foolish mistake. Thank you for patiently answering.


---- Replied Message ----
| From | Marc T. Henry de ***@***.***> |
| Date | 12/06/2024 02:07 |
| To | Exawind/amr-wind ***@***.***> |
| Cc | May0048 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Exawind/amr-wind] The "Header" file cannot be opened (Issue #1386) |

Are you sure you have the relative paths right?

**Comment by marchdf** [comment]
Please close this if fixed.  Thanks!
