### ISSUE TITLE
FLLC type specification for ALM is not working

### ISSUE THREAD

**Issue by rthedin** [Exawind/amr-wind#1407]
## Bug description
Trying to run an OpenFAST-coupled case using the FLLC for the actuator line and I'm unable to specify `Actuator.TurbineFastLine.fllc_type`. I'm not sure what this entry is expecting and [as per](https://exawind.github.io/amr-wind/user/inputs_Actuator.html#input_param-Actuator.FixedWingLine.fllc_type) the readthedocs I would think it's either `constant_chord` or `variable_chord`.

I believe the error is on the following line:
https://github.com/Exawind/amr-wind/blob/bb0e9dcc59c694812a03703199ade0a3984161d5/amr-wind/wind_energy/actuator/FLLC.cpp#L115

## Steps to reproduce
Add `Actuator.TurbineFastLine.fllc_type = <any_string>` to the `Actuator` part of the input file when `Actuator.TurbineFastLine.fllc = 1`.

To reproduce: start from [`act_fixed_wing_fllc.inp`](https://github.com/Exawind/amr-wind/blob/v3.2.0/test/test_files/act_fixed_wing_fllc/act_fixed_wing_fllc.inp) and add the line extra line with
```
sed -i '/Actuator\.FixedWingLine\.fllc = 1/a Actuator.FixedWingLine.fllc_type = variable_cord' act_fixed_wing_fllc.inp
```

1. Compiler used
   - [x] oneapi (Intel)
2. Operating system
   - [x] Linux
3. Hardware:
   - [x] CPU
4. Machine details ():
Kestrel

7. Error (paste or attach):
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
```

## Expected behavior
It shouldn't give an error like this one. I believe `variable_chord` is the default behavior so it should take that input.

## AMR-Wind information

```
==============================================================================
                AMR-Wind (https://github.com/exawind/amr-wind)

  AMR-Wind version :: v3.2.0
  AMR-Wind Git SHA :: bb0e9dcc59c694812a03703199ade0a3984161d5
  AMReX version    :: 24.09-45-g6d9c25b989f1

  Exec. time       :: Fri Dec 13 13:50:21 2024
  Build time       :: Dec 13 2024 12:12:21
  C++ compiler     :: IntelLLVM 2023.2.0

  MPI              :: ON    (Num. ranks = 64)
  GPU              :: OFF
  OpenMP           :: OFF

  Enabled third-party libraries:
    NetCDF    4.9.2
    OpenFAST

           This software is released under the BSD 3-clause license.
 See https://github.com/Exawind/amr-wind/blob/development/LICENSE for details.
------------------------------------------------------------------------------
```

## Additional context
The readthedocs is [missing](https://exawind.github.io/amr-wind/user/inputs_Actuator.html#input_param-Actuator.FixedWingLine.fllc_type) details on what is the default for such option. From the source code, I see `variable_chord` is the default, but it would be nice to have it on the docs
https://github.com/Exawind/amr-wind/blob/bb0e9dcc59c694812a03703199ade0a3984161d5/amr-wind/wind_energy/actuator/FLLC.cpp#L113

**Comment by mbkuhn** [comment]
Hey Regis, it looks like there is a typo in your sed line, because it has "variable_cord" instead of "variable_chord". This is probably why you got the error. But you have a good point about the documentation and the cryptic error message.

Because this input variable has only two options, it would probably be easier and more obvious to have it as "fllc_constant_chord_formulation = true/false" instead of having the user need to input "variable_chord" or "constant_chord". What do you think? Would you prefer me to just update the documentation and the error message, or should I also change the input argument?

**Comment by rthedin** [comment]
Oof, thanks for noticing the typo. Still- I'm pretty sure I've run into situations like this before and the error just said something long the lines of value not recognized. Can the error message be something like that?

I don't have any preferences regarding a bool vs strings. On one hand, the string is nice because you can specify any other formulation, but on the other hand, are we really going to have more than 2 formulations in there? I don't see necessarily any advantage so I'd vote for the simpler and less time-consuming one: update the documentation and add some more descriptive error message.

As a note, within the OpenFOAM community there is the "banana" term. It's often suggested that the user give "banana" to whatever input he/she does not know the options. That way the code crashes and prints the actual available options, along with the message that "banana" isn't recognized. For some reason I thought this was already the case with AMR-Wind-- not sure if it is and Tony just missed it with this FLLC option.

**Comment by mbkuhn** [comment]
I like that banana term! This is a unique thing that you've found -- looks like it's the only time that std::map is used for translating between input strings and different implementations, instead of just ordinary conditionals.

I'll get to work on the documentation + error message improvements soon.
