### ISSUE TITLE
Particles reader in Paraview 5.13.1 is broken

### ISSUE THREAD

**Issue by rthedin** [Exawind/amr-wind#1417]
The latest Paraview version 5.13.1 is no longer able to open sampling output in native/particle format. It works fine in Paraview 5.11.*. I have not tested 5.12. It could be that Paraview has updated their readers and they broke compatibility. 

Here's a screenshot of the error:
![image](https://github.com/user-attachments/assets/e866fbdd-ae9c-437e-bf87-2410332e5bc4)

**Comment by moprak-nrel** [comment]
If the same file is working within Paraview `5.11.x` and failing in `5.13.x`, I'm inclined to say this is a Paraview issue and not an amr-wind issue.

To debug this a bit more, which version of amr-Wind did you run this case with? Have you had other successful instances where things worked with Paraview `5.13.x`?

**Comment by rthedin** [comment]
I agree with you. I've chatted with Michael and he suggested I posted the issue here so it's documented.

To your questions, I used AMR-Wind 3.2.0. I'm not a heavy Paraview user (let alone latest versions) and I'm unable to comment further on other things working. This bug has been brought to my attention by the TotalEnergies team.

**Comment by marchdf** [comment]
I pinged the amrex slack channel to see if anyone has seen this.

**Comment by marchdf** [comment]
FWIW, I see the same. 5.10 seems fine and 5.13 does same as you.

<img width="739" alt="Screenshot 2024-12-19 at 3 45 54 PM" src="https://github.com/user-attachments/assets/7c8db5af-cd2f-4a0d-93fb-06405d85e695" />

**Comment by mbkuhn** [comment]
> I pinged the amrex slack channel to see if anyone has seen this.

Thanks Marc, that was my plan: getting this recorded here and then sharing with the amrex folks who may also have contacts w/ Paraview.

**Comment by marchdf** [comment]
I have reported this issue to a developer at Kitware and created an issue on their site: https://gitlab.kitware.com/paraview/paraview/-/issues/22835.  Closing this issue as being tracked elsewhere.
