### ISSUE TITLE
Plane Averaging – deprecate ASCII output and switch to binary format as default

### ISSUE THREAD

**Issue by sayerhs** [Exawind/amr-wind#168]
- Use NetCDF format (similar to sampling and ABL boundary I/O) to output planar averaging statistics. 
- Minimize code duplication in I/O logic for ASCII outputs

**Comment by gantech** [comment]
I suppose https://github.com/Exawind/amr-wind/pull/175 addressed this already?

**Comment by marchdf** [comment]
Looks like this was fixed so I am closing this. Please reopen if not.
