### ISSUE TITLE
error: 'Gpu' has not been declared

### ISSUE THREAD

**Issue by rd-contr** [Exawind/amr-wind#204]
I am trying to build the latest amr-wind on a Cray XC50 with GCC 7.2.0 and receive an error when it is trying to compile FieldPlaneAveraging.cpp. Current git repo hash, cmake statement, and compile errrors are in the attached text file.

[amr_wind_build_error.txt](https://github.com/Exawind/amr-wind/files/5196993/amr_wind_build_error.txt)

**Comment by michaeljbrazell** [comment]
we haven't tested openmp thoroughly, try turning that off

**Comment by michaeljbrazell** [comment]
but yes, good catch, it is a bug. It should probably be amrex::Gpu::notInLaunchRegion()

**Comment by rd-contr** [comment]
Removing the openmp option in cmake cleared out the error. Many thanks.

**Comment by sayerhs** [comment]
Fix implemented in 3ad40012
