### ISSUE TITLE
Reuse MacProjector and NodalProjector instances

### ISSUE THREAD

**Issue by sayerhs** [Exawind/amr-wind#222]
**Issue:** Currently AMR-Wind creates a new `amrex::MacProjector` and `amrex::NodalProjector` within predictor and corrector steps during time integration. When using hypre as external solver (or bottom solver), this does not allow reuse of hypre setup and preconditioner and is inefficient. 

**Desired:** Store instances of `amrex::MacProjector` and `amrex::NodalProjector` across timesteps resetting instances only after a regrid.

**Comment by marchdf** [comment]
From what I can tell in the code, this looks done. Please reopen if not.
