### ISSUE TITLE
Inflow outflow last time-step

### ISSUE THREAD

**Issue by tonyinme** [Exawind/amr-wind#353]
When running an inflow/outflow simulation, there are some checks in the code that do not allow the last time-step to be completed if the last time of the simulation is the same as the last time in the boundary data.

This error shows up at the last time-step:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Assertion `(m_in_times[0] <= time) and (time < m_in_times.back())' failed, file "/home/lmartine/amr-wind/amr-wind/wind_energy/ABLBoundaryPlane.cpp", line 483
  ```

**Comment by marchdf** [comment]
@tonyinme maybe this has been resolved or I am not understanding the issue. I can have output data that runs until t=5 and then have the other one read the data and complete with
```
Step: 18 dt: 0.1 Time: 4.9 to 5
CFL: 0.0534213 (conv: 0.0530572 diff: 0 src: 0.00441036 )

Godunov:
  System                     Iters      Initial residual        Final residual
  ----------------------------------------------------------------------------
  MAC_projection                 8          0.0435747791       9.183101599e-14
  temperature_solve              0                     0                     0
  velocity_solve                 3        0.001731089974       1.154631946e-13
  Nodal_projection               6       0.0006506903727       3.128871945e-16

WallClockTime: 18 Pre: 0.00498 Solve: 2.578 Post: 0.0378 Total: 2.621
Solve time per cell: 0.0001865
```

Obviously, step 19 that goes from 5.0 to 5.1 won't complete. But I think that is to be expected? Here are the input files I am using:
- [abl_bndry_output.inp.txt](https://github.com/Exawind/amr-wind/files/10116318/abl_bndry_output.inp.txt)
- [abl_bndry_input.inp.txt](https://github.com/Exawind/amr-wind/files/10116322/abl_bndry_input.inp.txt)

**Comment by marchdf** [comment]
Closing. Please reopen if I didn't address the issue.

**Comment by tonyinme** [comment]
Sounds good @marchdf . It looks like this has been addressed and I have not run into this in a while.
