### ISSUE TITLE
Regression tests not added to nightly test suite

### ISSUE THREAD

**Issue by sayerhs** [Exawind/amr-wind#383]
Several regression test directories added to [test/test_files](https://github.com/Exawind/amr-wind/tree/main/test/test_files) are not run nightly. Most appear to be related to MultiPhase

- [x] `abl_godunov_weno`
- [x] `dam_break_godunov`
- [x] `sloshing_tank`
- [x] `act_fixed_wing`
- [x] `act_flat_plate`

**Comment by sayerhs** [comment]
Actuator tests are being handled in #381

**Comment by sayerhs** [comment]
Dam break and sloshing tank handled in #379

**Comment by michaeljbrazell** [comment]
abl_godunov_weno #384
