### ISSUE TITLE
Parallel run of AMR-Wind with OpenFAST/ALM 

### ISSUE THREAD

**Issue by lawrenceccheung** [Exawind/amr-wind#415]
I'm running an OpenFAST simulation and hitting an error when I use a specific number of cores.  

The case is basically the same as @tonyinme's [nrel5mw example](https://github.com/tonyinme/amr-wind/blob/openfast_example/test/test_files/act_openfast_nrel5mw/alm.i), with a different turbine model in place (see model [here](https://github.com/NREL/openfast-turbine-models/tree/f/IEA-scaled-2.5-116/IEA-scaled/NREL-2.5-116)).

It crashes when I use two ranks, but runs fine if I use any other number of cores (1, 3, 4, ...).  The error message I get is: 
```
Step: 2 dt: 0.1 Time: 0.1 to 0.2
CFL: 0 (conv: 0 diff: 0 src: 0 )
terminate called after throwing an instance of 'std::runtime_error'
  what():  ParticleContainer::locateParticle(): invalid particle.
```

Interestingly, it works fine on 2 cores if I change the mesh count, or remove any of the refinement regions.  Also, the nrel5mw example works fine on any number of cores.

The input file and openfast model can be downloaded here:
[DebugALM.tar.gz](https://github.com/Exawind/amr-wind/files/6556391/DebugALM.tar.gz)
And this is the SHA of the AMR-Wind code I'm using (basically Tony's branch):
```
==============================================================================
                AMR-Wind (https://github.com/exawind/amr-wind)

  AMR-Wind version :: 08fd758-DIRTY
  AMR-Wind Git SHA :: 08fd7587d9f6eb109c88091bb9e93dde550767e1-DIRTY
  AMReX version    :: 21.04

  Exec. time       :: Thu May 27 13:37:31 2021
  Build time       :: May  3 2021 19:33:58
  C++ compiler     :: GNU 7.2.0

  MPI              :: ON    (Num. ranks = 2)
  GPU              :: OFF
  OpenMP           :: OFF

  Enabled third-party libraries: 
    NetCDF    4.7.3
    OpenFAST  
```

I will continue debugging the case and let you know if I find anything else going on.

Lawrence

**Comment by sayerhs** [comment]
Does it also crash with the main branch?

The error message indicates that the particle reinitialization is not performed correctly. Can you post the full stack trace?

**Comment by sayerhs** [comment]
@lawrenceccheung also why is your CFL zero? Can you verify that the OpenFAST actuator locations are sane?

**Comment by lawrenceccheung** [comment]
Oh whatever the bug is, this issue disappears on the latest main branch.  I had tested it from a build of the main branch back on May 4 (SHA: d5555c77aa8267047503feaa3ab7ecdf372c674f), and it was failing, but the latest main branch (319ad956f0f85fbe2c41fbec97b69f7b63a190c9) seems to work.

It's strange, when it runs, the CFL's are normal and the turbine operates okay.  But using the older branches, the code just spits out zero CFL's if you use 2 proc's.

Lawrence
