### ISSUE TITLE
Boundary conditions

### ISSUE THREAD

**Issue by ArtemTKir** [Exawind/amr-wind#420]
Hello.
Answer me please how i can to do specific time-depends boundary conditions?  I want to model jet/flow from left boundary where V_x = const*sin(t) in 5<y<7. My box have parameters xlo, ylo = 0 and xhi, yhi = 10.

**Comment by michaeljbrazell** [comment]
Hi, you can add your own user defined function (UDF) here: https://github.com/Exawind/amr-wind/tree/main/amr-wind/physics/udfs

use linear and power law as examples but note that they don't use time which is the 4th input

```

amrex::ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) {         
   for (int n = 0; n &lt; ncomp; ++n) {                
      dop({i, j, k}, marr, geomData, time, {}, n);        
    } });   }}

**Comment by michaeljbrazell** [comment]
@gantech can you provide an input file snippet for udf's?

**Comment by ArtemTKir** [comment]
Thanks, its works. I think that to add it in examples or/and documentation good idea.
