### ISSUE TITLE
GeometryRefinement level specification

### ISSUE THREAD

**Issue by lawrenceccheung** [Exawind/amr-wind#423]
I think there's a bug with the `GeometryRefinement` level specification.  If I try something like this:

```
tagging.labels                           = box1 
tagging.box1.type                        = GeometryRefinement
tagging.box1.shapes                      = box1
tagging.box1.level                       = 0
tagging.box1.box1.type                   = box
tagging.box1.box1.origin                 = -1160.0 -580.0 -580.0
tagging.box1.box1.xaxis                  =  3480.0  0.0    0.0
tagging.box1.box1.yaxis                  =  0.0     1160.0 0.0
tagging.box1.box1.zaxis                  =  0.0     0.0    1160.0
```
The refinement in `box1` happens at all levels and I get a larger mesh than I expected.  However, `min_level` and `max_level` specifications seem to be working fine.

Looking at `GeometryRefinement.cpp`:  
https://github.com/Exawind/amr-wind/blob/9f619d1218d716281c6cf6b97e1fe13dd8953e48/amr-wind/utilities/tagging/GeometryRefinement.cpp#L37-L39
should that be `m_set_level > -1` instead?

Lawrence

**Comment by sayerhs** [comment]
@lawrenceccheung for what you want to do, I'd intended to  use `box1.max_level = 0`.  But yes, your suggestion makes sense, please go ahead and submit a PR.
