### ISSUE TITLE
Inflow/outflow mesh refinement

### ISSUE THREAD

**Issue by tonyinme** [Exawind/amr-wind#425]
I am working on creating an example for inflow/outflow simulations with an openfast actuator line turbine and grid refinement. We currently need some workarounds/hacks in order to get this working. 

This workaround was done by following the recommendations from @gantech.

The steps to make it work is as follows:

0. Modify the code in [ABLBoundaryPlane.cpp ](https://github.com/Exawind/amr-wind/blob/main/amr-wind/wind_energy/ABLBoundaryPlane.cpp) by setting `nlevels=1`. If this is not done, the boundary data cannot work if there are more than one refinement levels inside the domain.

1. **Simulation 1:** Run ABL precursor simulation with boundary data sampling. (This works without a problem)

2. **Simulation 2:** Create the refined mesh by running a simulation starting from Simulation 1 for as many time-steps as refinement levels needed and setting `time.regrid_interval = 1` in the input file. For example, if we want 2 levels of refinement for the turbine simulation, the simulation 2 will be run for 2 time-steps in order to create the new refined mesh.

3. **Simulation 3:** Run a new simulation with the inflow/outflow starting from the last time-step of simulation 2 which contains the refined mesh.

Steps 0 and 2 are hacks that we have in order to make it work. Ideally, we would not need those steps.
I am looking for your feedback on how to improve this?

One option is to hardcode `nlevels=1` in [ABLBoundaryPlane.cpp ](https://github.com/Exawind/amr-wind/blob/main/amr-wind/wind_energy/ABLBoundaryPlane.cpp).
Ideally, Simulation 2 would not be needed and simulation 3 would automatically refine the mesh in the first time step.

Please let me know what ideas you have to improve this.

@michaeljbrazell @sayerhs @gantech @marchdf @gdeskos @shashankNREL

**Comment by sayerhs** [comment]
@tonyinme 

- We should not have to hard code `nlevels` in ABLBoundaryPlane. The code should be refactored to only apply refinements for levels that are available in the saved precursor file. However, one question we have to agree on is whether we will have refinement levels touching the precursor inlet boundaries. Handling all use cases is going to be a bit tricky. 
- Simulation 2 should not be required, that was a workaround for getting the IEA simulations done (*horror*). Instead what is needed is a `regrid_on_restart` setup during initialization. Unfortunately, this wasn't implemented when AMR-wind refinement infrastructure was implemented. It is a couple of lines of code in the initialization logic to make this happen.

**Comment by marchdf** [comment]
Hi all, I will be looking into this (as well as the similar issues in #414 )
