### ISSUE TITLE
Boundary planes for `xhi`/`yhi` planes

### ISSUE THREAD

**Issue by lawrenceccheung** [Exawind/amr-wind#429]
While we're discussing making changes to the boundary planes I/O, how difficult would it be to also to capture/reapply data on the  `xhi`/`yhi` planes:

https://github.com/Exawind/amr-wind/blob/57645d5369a89a616e04c45803ac090097196c90/amr-wind/wind_energy/ABLBoundaryPlane.cpp#L230-L231

https://github.com/Exawind/amr-wind/blob/57645d5369a89a616e04c45803ac090097196c90/amr-wind/wind_energy/ABLBoundaryPlane.cpp#L600-L602

Obviously this is less urgent than fixing the current issues, but for one of the AWAKEN cases we may have a wind direction that will make use of that (rotating the entire farm and wind direction to fit the `xlo`/`ylo` planes is possible, but not the desired approach).

Thanks,
Lawrence

**Comment by marchdf** [comment]
Hi @lawrenceccheung, in theory, this isn't difficult... but hitting all the corner cases is the tricky part. It comes down to a bunch of `if` conditions to get right. If you have a use-case/input file/setup to try this on, I would be happy to see if I can make the necessary changes to make it work.
