### ISSUE TITLE
AMR-Wind fails to compile with HIP

### ISSUE THREAD

**Issue by afanfa** [Exawind/amr-wind#430]
Hello all,
as shown by the CI, PR #413 doesn't compile correctly with HIP.
Wouldn't be appropriate for all the member functions (as for operator[]) of the Slice struct to have the AMREX_GPU_HOST_DEVICE attribute?

**Comment by jrood-nrel** [comment]
We are currently letting CI install the latest HIP when 4.1.1 is required. See https://github.com/AMReX-Codes/amrex/blob/baf0d4cd96fa81ace1c964a2e5601685e97d41f6/.github/workflows/dependencies/dependencies_hip.sh#L19 

I will update the CI to use 4.1.1.

**Comment by afanfa** [comment]
Unfortunately this issue will not be solved by using ROCm-4.1.1 (or future versions, like ROCm-4.3, I have tried, I am an AMD employee). What seem to work is to add AMREX_GPU_HOST_DEVICE in front of the member function of Slice struct in amr-wind/core/Slice.H

For example:

pointer data() { return ptr_begin; } -> AMREX_GPU_HOST_DEVICE pointer data() { return ptr_begin; }
const_iterator data() const { return ptr_begin; } -> AMREX_GPU_HOST_DEVICE const_iterator data() const { return ptr_begin; }

**Comment by jrood-nrel** [comment]
Ah, ok. Thanks for the tip. I will try to get this working again soon then.
