### ISSUE TITLE
Processing line sampling data

### ISSUE THREAD

**Issue by joejoeyjoseph** [Exawind/amr-wind#438]
Hello, I am trying to generate and analyze the data vertically at a point, and I turned on the `LineSampler` option. After the simulation is finished, in `/post_processing/sampling0xxxx`, I notice different types of binary files exist (`DATA_0xxxx` and `Particle_H`). I am unsure which files contain the line sampling data, I cannot differentiate the two points/labels I specified (`ls1` and `ls2` below), and I do not know how to use the binary files efficiently. Please kindly give me some suggestions. 

The following is the setting in my abl file: 

`incflo.post_processing = sampling`
`sampling.output_frequency = 3000`
`sampling.output_format = "native"`
`sampling.labels = ls1 ls2`
`sampling.fields = velocity temperature`

`sampling.ls1.type = LineSampler`
`sampling.ls1.num_points = 200`
`sampling.ls1.start = 500.0 500.0 0.0`
`sampling.ls1.end = 500.0 500.0 1000.0`

`sampling.ls2.type = LineSampler`
`sampling.ls2.num_points = 200`
`sampling.ls2.start = 2800.0 2800.0 0.0`
`sampling.ls2.end = 2800.0 2800.0 1000.0`

Thank you in advance. 

Joseph

**Comment by sayerhs** [comment]
@joejoeyjoseph The data is saved in native AMReX particle format. You can use the [python script](https://github.com/Exawind/amr-wind/blob/main/tools/amrex_particle.py) in the `tools` directory to extract the data into a Pandas Dataframe. 

```python
from amrex_particle import AmrexParticleFile

# Load data from 1000th timestep in  the run directory (containing input file)
pfile = AmrexParticleFile.load(1000)

# get dataframe
df = pfile()
```
