### ISSUE TITLE
Downstream turbine not visible for 1 CPU used in simulation

### ISSUE THREAD

**Issue by raphael-kinvi** [Exawind/amr-wind#454]
Hello the community,
I run the Nalu-wind example with uniform air inflow using the Exawind platform and Actuator Line Method (ALM) coupled with Openfast. 
The downstream turbine is not visible when I post-processed simulations run using only 1 CPU. However it seems ok for parallel simulations (8cores)

**Comment by sayerhs** [comment]
@raphael-kinvi Can you confirm that you're running [AMR-Wind](https://github.com/exawind/amr-wind) (this repo) and not [Nalu-Wind](https://github.com/exawind/nalu-wind)? AMR-Wind supports multiple turbines even on a single process, but Nalu-Wind requires number of MPI processes to be greater than or equal to the number of actuator line turbines in the simulation.

**Comment by raphael-kinvi** [comment]
Excuse me, I am not in the right repo. I am running Nalu-Wind and you have answered my question.
Thank you
