### ISSUE TITLE
How can I record the average flow rate in a section to a file?

### ISSUE THREAD

**Issue by ArtemTKir** [Exawind/amr-wind#460]

**Comment by michaeljbrazell** [comment]
you can average the entire flow field https://github.com/Exawind/amr-wind/tree/main/amr-wind/utilities/averaging https://exawind.github.io/amr-wind/user/inputs_Averaging.html

or output planes of data https://exawind.github.io/amr-wind/user/inputs_Sampling.html#sampling-on-one-or-more-planes post process the planes after to get an average.

**Comment by ArtemTKir** [comment]
I was adding parameters in input_file (amr-wind/test/test_files/uniform_ct_disk):

**sampling.labels = line1
sampling/line1.type       = LineSampler
sampling/line1.num_points = 10
sampling/line1.start      = 0.0 0.0 0.0
sampling/line1.end        = 10.0 0.0 0.0**

but it does not work. Amr-wind writed:
**Unused ParmParse Variables:
  [TOP]::io.KE_int(nvals = 1)  :: [0]
  [TOP]::sampling.labels(nvals = 1)  :: [line1]
  [TOP]::sampling/line1.type(nvals = 1)  :: [LineSampler]
  [TOP]::sampling/line1.num_points(nvals = 1)  :: [10]
  [TOP]::sampling/line1.start(nvals = 3)  :: [0.0, 0.0, 0.0]
  [TOP]::sampling/line1.end(nvals = 3)  :: [10.0, 00.0, 0.0]**

How do I make "sampling" work?

How do I make "averaging" work?

**Comment by michaeljbrazell** [comment]
make sure you have this line `incflo.post_processing = sampling` and then change the slashes to . 
`sampling/line1.type`   ---> `sampling.line1.type`
and do that for all of them with slashes

**Comment by ArtemTKir** [comment]
Thanks, its work.
I run with:
**incflo.post_processing = sampling 
sampling.output_frequency = 10
sampling.output_format = native
sampling.fields = velocity
sampling.labels = line1
sampling.line1.type       = LineSampler
sampling.line1.num_points = 12
sampling.line1.start      = 0.0 5.0 4.0
sampling.line1.end        = 12.0 5.0 4.0**

I tried to open the files "post_processing / sampling000 * / Header" with "visit", but the error was displayed:

_VisIt could not read from the file ".../amr-wind/test/test_files/uniform_ct_disk/post_processing/sampling00000/Header".

The generated error message was:

There was an error opening .../amr-wind/test/test_files/uniform_ct_disk/post_processing/sampling00000/Header. It may be an invalid file.
VisIt tried using the following file format readers to open the file: Boxlib2D, Boxlib3D, Silo

If you know the specific format reader VisIt should use to
read this data, you can use Open As... (GUI) or
'-o <file>,<plugin> (CL arg.) and identify that specific reader
for VisIt to try. This will possibly give more information on
the exact error._

How can I read and visualize this data?

I also tried the "ascii" option. Here's what was written to the file:
**11
0
3
3
0
1.2727272727273 5 4 4 0 3 0 3 7.96653725103504 1.96390465620662e-07 6.02957983949373e-06 
8 5 4 1 0 0 0 0 -4.12794840353267 3.46497317519397e-06 1.54872777903166e-05 
...
 **

The first 3 columns are coordinates. The last 3 columns are the x, y, z components of the velocity? What do the rest mean?

**Comment by michaeljbrazell** [comment]
Do you have access to NetCDF? If so, that might be easier to work with. Check this out: https://github.com/Exawind/amr-wind/issues/463

**Comment by marchdf** [comment]
@ArtemTKir I am going to assume this was resolved. If not, please reopen.
