### ISSUE TITLE
AmrexParticleFile function error

### ISSUE THREAD

**Issue by joejoeyjoseph** [Exawind/amr-wind#463]
Hello, I tried to use the `AmrexParticleFile` function, and it gave me errors when I was loading the data. I figured out that the error is related to `pidx` and the offset between different sample towers in `amrex_particle`. I tried to debug it but I could not completely eliminate the error. 

I uploaded a directory of my sampling data at
https://github.com/joejoeyjoseph/awaken-code/tree/main/eagle/sampling60000 

Please let me know. Thank you in advance.

_Originally posted by @joejoeyjoseph in https://github.com/Exawind/amr-wind/discussions/451#discussioncomment-1058699_

**Comment by michaeljbrazell** [comment]
Are you using the native format for sampling? It's probably easier to work with netcdf, is netcdf available on your machine?

**Comment by joejoeyjoseph** [comment]
I am using native format for sampling, and I have netcdf set up. According to the user manual, two options in `sampling.output_format` are available, `native` and `ascii`, and the latter is for debugging only. May I know how to use netcdf in the sampling function?

**Comment by sayerhs** [comment]
@joejoeyjoseph If AMR-Wind was compiled with NetCDF support, then the default format for output is automatically set to `netcdf`. Since you're getting `native` output, it indicates that either your AMR-Wind build is not linked to NetCDF or you manually set the output format to `ascii` (I am assuming it is the former). You can verify this by looking at the banner when you run AMR-Wind, it will list NetCDF in the list of "additional third-party libraries enabled". If it is not present, you'll want to reconfigure the build to link to NetCDF. 

Would you mind sharing the full python stacktrace for the error your seeing with `pidx`?

**Comment by joejoeyjoseph** [comment]
@sayerhs Thank you for the explanation. I am running AMR-Wind and analyzing its outputs on NREL's Eagle, and the system is scheduled for maintenance this week. I will check the NetCDF configuration of AMR-Wind and send over the stack trace of the error when it is back online. Thank you again.

**Comment by joejoeyjoseph** [comment]
Hello, 

I am using Python 3.8.10, and the code yields the following error based on the binary sampling data I have (please refer to the first comment I wrote above). 

```python
from amrex_particle import AmrexParticleFile`

pfile = AmrexParticleFile.load(60000)

df = pfile()

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-1dad06dabb22> in <module>
     11 pfile = AmrexParticleFile.load(60000)
     12 
---> 13 df = pfile()

~/amrw/main-amr-wind/tools/amrex_particle.py in __call__(self)
     47         if not hasattr(self, "df"):
     48             self.parse_header()
---> 49             self.load_binary_data()
     50         return self.df
     51 

~/amrw/main-amr-wind/tools/amrex_particle.py in load_binary_data(self)
    105                 for i, ii in enumerate(range(0, nints * npts, nints)):
    106                     pidx = ivals[ii + 2]
--> 107                     idata[pidx, 0] = pidx
    108                     idata[pidx, 1] = ivals[ii + 3]
    109                     idata[pidx, 2] = ivals[ii + 4]

IndexError: index 802 is out of bounds for axis 0 with size 800
```

I tried to change the values of `pidx` in line 106 (e.g. based on the number of the `sampling.labels` listed in the `abl` input file), and such fix could make the code run error-free, but the resultant data frames are still erroneous (e.g. NaN values in some elements, etc). 

The good news is, I checked my AMR-Wind configuration and NetCDF (4.7.3) is listed as an enabled third-party library. In a test run, I turned off `sampling.output_format = "native"` and this leads to `post_processing/sampling00000.nc`, which contains error-free sampling data. Hence I am able to produce the sampling data I want. 

The documentation at https://exawind.github.io/amr-wind/user/inputs_Sampling.html might want to include that even though the default for `sampling.output_format` is `native`, leaving the line out would result in NetCDF sampling data, when the library is enabled. 

Thank you for your help. 

Joseph

**Comment by michaeljbrazell** [comment]
Thanks Joseph, I updated the docs to include the NetCDF option. Can we close this issue now?

**Comment by joejoeyjoseph** [comment]
Sure, we can close this issue. Please be aware that the `amrex_particle` code can potentially cause problems.
