### ISSUE TITLE
CMake Error at while installing amr-wind: string sub-command STRIP requires two arguments.

### ISSUE THREAD

**Issue by maxshatsky** [Exawind/amr-wind#472]
I was following instruction from here:
https://exawind.github.io/amr-wind/user/build.html

Running command
$ cmake -DAMR_WIND_ENABLE_TESTS:BOOL=ON ../

has led to the following error:
CMake Error at submods/amrex/Tools/CMake/AMReXUtils.cmake:20 (string):
  string sub-command STRIP requires two arguments.

Investigation of the mentioned file has shown the difference between strings containing STRIP command:

![image](https://user-images.githubusercontent.com/46995837/129190525-4eb7aaaa-0494-46dd-8fcd-20fcdf3ef4ac.png)

string( STRIP ${_tmp} _tmp ) at line 20
VS
string(STRIP "${_tmp}" _tmp ) at line 32

Solution:
I followed a tip described here:
https://stackoverflow.com/questions/26585513/cmake-error-with-string-sub-command-strip-requires-two-arguments

adding the same quotas to line 20 seemed to solve the problem.

**Comment by marchdf** [comment]
Hi, thank you for reporting this! Unfortunately, this is happening in the AMReX package and not in AMR-Wind. Would you mind reporting your issue and fix to the AMReX community? You can create an issue here: https://github.com/AMReX-Codes/amrex

**Comment by maxshatsky** [comment]
Oh, you are right, the issue comes from original AMReX and now is reported, ty.
