### ISSUE TITLE
Virtual Lidars

### ISSUE THREAD

**Issue by tonyinme** [Exawind/amr-wind#493]
This is a feature request for virtual lidars.
This feature is needed for the DOE Rotor Aerodynamics, Aeroelastics and Wake (RAAW) Experiment.

Examples of virtual lidars in other codes are here:
[SOWFA](https://github.com/NREL/SOWFA/tree/master/src/postProcessing/functionObjects/utilities)
[Nalu-Wind](https://github.com/Exawind/nalu-wind/blob/master/src/wind_energy/SyntheticLidar.C)

The lidars needed are:
1. Scanning Lidar
2. Profiling Lidar
3. Spinner Lidar

**Comment by tonyinme** [comment]
First lidar has been implemented: https://github.com/Exawind/amr-wind/pull/502

Next steps:

- [ ] Add capability to sample more than once per -time-setp.
- [ ] Add DTU Spinner Lidar

**Comment by tonyinme** [comment]
Code to sample more than once within a time-step has been added here: https://github.com/Exawind/amr-wind/pull/513

**Comment by mbkuhn** [comment]
@tonyinme looks like this feature was completed. can we close this issue?

**Comment by tonyinme** [comment]
Hey @mbkuhn , it is almost complete. 
I believe that @ndevelder is finalizing the last PR needed to incorporate the full capability of the spinner lidar.

**Comment by mbkuhn** [comment]
I believe this has been completed with PR #954 and #1000. @tonyinme can you confirm?

**Comment by tonyinme** [comment]
Yes, this was completed. 
Thanks @ndevelder and @mbkuhn !
