### ISSUE TITLE
Incorporating outside development branches as draft PR's 

### ISSUE THREAD

**Issue by lawrenceccheung** [Exawind/amr-wind#499]
Based on the discussions from our group, we are starting to see issues where a lot of simulations and development work is happening on people's personal branches.  This is pretty natural, but eventually leads to situations where simulations are hard to replicate because of unknown executable versions, massive commits when it comes time to merge things back in, duplicated code development, a whole host of other issues.

I think some collective effort will be required, but we can set up a transparent, collaborative environment where people's progress can be easily seen through draft PR's, and where we all feel welcome to share our code and solicit feedback without any guilt or pressure.

Let me start a github issue on this to collect people's comments and track progress towards this goal.  From our discussions, the following actions would be a nice step forward:
- Creating a set of guidelines and expectations for developers, where ECP/Exawind funded developments should be opened as draft pull requests, with
  - no expectation of being forced to merge it into the main branch later on
  - no expectations of a formal code review in draft stage
  - smaller, regular commits so that things don't pile up
- Creating a set of guidelines for code reviewers, with constructive criticism being the rule and everyone welcoming code from all experience levels 
- Creating a presentation with these best practices, bringing it up to the PI's, and discussing this at the next Exawind meeting.

Lawrence

**Comment by marchdf** [comment]
@lawrenceccheung this has been open for a while. Can we close it? If need be we can open a new one with the stuff that is still outstanding since you first opened this in 2021. Feels like some of this might have been addressed?

**Comment by marchdf** [comment]
Closing, please reopen if need be.
