### ISSUE TITLE
AMReX_SetupCUDA is deprecated for CMake >= 3.20

### ISSUE THREAD

**Issue by yuya737** [Exawind/amr-wind#501]
I have been building AMR-Wind on Summit as part of my testing for Ascent. With CMake version 3.20, I am getting the warning 

`AMReX_SetupCUDA is deprecated for CMake >= 3.20: it will not be processed!`

and ultimately have link issues with CUDA symbols. 

AMReX appears to have changed their CMake-ry for CUDA with this change: https://github.com/AMReX-Codes/amrex/pull/2012 

I tried modifying `cmake/amr-wind-utils.cmake` to remove the lines 
```
if (AMR_WIND_ENABLE_CUDA)
     include(AMReX_SetupCUDA)
   endif()
```

but this did not work for me.  

Ascent requires CMake 3.20 and above. That said, I have a workaround for now, which is to build Ascent with CMake 3.20 and AMR-Wind with 3.18 and the two still appear to work together.

**Comment by jrood-nrel** [comment]
Hello. I'm using CMake 3.21.3 on Summit for AMR-Wind and I do not experience link issues. I always see the `AMReX_SetupCUDA` warning. Can you provide the link error and any more information?
