### ISSUE TITLE
NetCDF 

### ISSUE THREAD

**Issue by tonyinme** [Exawind/amr-wind#507]
We have seen a slowdown of ABL precursor simulations when using NetCDF boundary data output on Eagle and Summit.
There seems to be a size limit and some cases are too big and won't run.
Some issues have been traced to the `put` call.

Specific cases:
- [ ] 900 x 450 inflow in x and y will not run
- [ ] 512 x 512 inflow in x sees a slowdown of 10 seconds per time-step

**Comment by ashesh2512** [comment]
I also want to add, we are putting 5 variables per every cell.

**Comment by sayerhs** [comment]
@tonyinme Do you see slowdown both during output as well as reading in the data, or just the output? It would be good if you could share the memory usage statistics for this case @michaeljbrazell and @marchdf  can help there. 

@marchdf  We might want to test this without parallel NetCDF for this case. Or switch to AMReX format.

**Comment by marchdf** [comment]
There's a lot of chatter about this going on. We have a meeting for this on Monday. My personal take is that we should have a switch to use native amrex format. Netcdf has been a headache since we first put it in the code...

**Comment by tonyinme** [comment]
Hey @sayerhs, I confirmed with @ashesh2512 and @neilmatula that most slowdowns are coming from output. However, there might be some others that have observed a slowdown with reading.

**Comment by psakievich** [comment]
After speaking with @gdsjaar today we've decided on this plan of attack:

1. Try using `NC_NETCDF5` instead of `NC_NETCDF4` for the parallel output. This uses an entirely separate parallel implementation and may perform better.  There is a limitation that each field must be less than `2^32` bytes with the `NC_NETCDF5` but it does not seem likely we will hit that limit any time soon, and this is simple to test.
2. Try using serialized output with manual gathering of the fields like we do for the sample plains
3. Try upgrading to `hdf5@1.12` and/or `netcdf@4.8.0` to see if newer performance optimizations help us out.

**Comment by ashesh2512** [comment]
@psakievich Regarding item no. 3, we have tried NetCDF 4.8.0. However, we haven’t tried it in conjunction with HDF5 1.12

**Comment by lawrenceccheung** [comment]
I'm working now with @psakievich to test out the `NC_NETCDF5` version.  Looks like there's still some bugs to fix.  However, I did obtain some baseline timing information for the problem on the Sandia machines as well.  I'm using the small IEA29 ABL test case [here](https://github.com/lawrenceccheung/IEATask29_precursor/tree/main/REF1_ABLIO/baseprecursor), which is 128 x 128 x 160, and the total size of boundary planes being written out is 2 x 160 x 128 = 40,960.  

Using 427b209 on attaway with 8 nodes/288 cores:
- without boundary plane I/O: 0.164308 sec/iter
- with boundary plane I/O: 3.24028 sec/iter

If we see any improvements with any of suggested ideas, I will let everyone know.

Lawrence

**Comment by pscrozi** [comment]
Michael D’mello from Intel suggested we might reach out to a couple of I/O / netcdf experts if needed:

Alfizah, Kurniawan kurniawan.alfizah@intel.com
or Kevin Harms (ANL)

**Comment by lawrenceccheung** [comment]
Although this isn't technically related to the NetCDF version, I also tested `b1e28426` with the native boundary I/O format from @michaeljbrazell (see [PR 557](https://github.com/Exawind/amr-wind/pull/557)) on the IEA29 test case.

Dumping out the the boundary planes in the native format averaged `0.232518` sec/iter, which is close to the performance without any boundary plane output.

Lawrence
