### ISSUE TITLE
KSGS issues on restart with refinement

### ISSUE THREAD

**Issue by neilmatula** [Exawind/amr-wind#515]
The OneEqKsgs84 turbulence model seems to sometimes have issues when restarting and adding refinement at the same time.
The residual reported for all equations becomes zero after the first timestep.
A small case that demonstrates the issue is defined by the two attached input files.
To reproduce the issue, run precursor.i, followed by turbine.i.
For reference, this was done on eagle using 64 processors.
The issue does not appear if there is no restart, or if there is only one level of refinement (max_level=1), or if Smagorinsky is used.
[issue.zip](https://github.com/Exawind/amr-wind/files/7721517/issue.zip)

**Comment by gantech** [comment]
`#¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨#
#        ADAPTIVE MESH REFINEMENT       #
#.......................................#
amr.n_cell              = 128 128 32    # Grid cells at coarsest AMRlevel
amr.max_level           = 2           # Max AMR level in hierarchy 
#¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨#
#              GEOMETRY                 #
#.......................................#
geometry.prob_lo        =   0.       0.     0.  # Lo corner coordinates
geometry.prob_hi        =   5000.  5000.  1000.  # Hi corner coordinates
geometry.is_periodic    =   1   1   0   # Periodicity x y z (0/1)
incflo.delp             =   0.  0.  0.  # Prescribed (cyclic) pressure gradient`

Does this uniformly refine the mesh across the entire domain?

**Comment by neilmatula** [comment]
No, it should refine according to the refinement blocks blocks at the very bottom, in the mesh refinement section.

**Comment by michaeljbrazell** [comment]
this might help: https://github.com/Exawind/amr-wind/pull/492

**Comment by tonyinme** [comment]
This [function call](https://github.com/Exawind/amr-wind/blob/c1531ecc7ccccef0956cb72e3461535375dbe4f6/amr-wind/equation_systems/tke/source_terms/KsgsM84Src.cpp#L59) throws an error in the debug build.

I am not entirely sure what this does, but this fix supresses the error: ` amrex::Box blo = amrex::adjCellLo(bx, dir, 1) & bx;`
Is this the right thing to do?

@michaeljbrazell @gantech @neilmatula

**Comment by rybchuk** [comment]
I ran into this issue as well in some of my convective simulation too, and I was seeing some weird behavior. If I picked one restart time (e.g. 10000 seconds), my simulation would run just fine. If I picked other restart times (e.g. 9000 seconds, 11000 seconds), my simulation would go to 0 CFL after just one timestep.

**Comment by mbkuhn** [comment]
Explanation in PR #942 .
