### ISSUE TITLE
Dynamic refinement question

### ISSUE THREAD

**Issue by sofYarikova** [Exawind/amr-wind#525]
Hello,

I tried to refine the base mesh, the refinement criteria is FieldRefinement. 
The following is the setting in my file:

----------------------------------------------------------------------------------------------------------------------------------------------
time.regrid_interval = 2
amr.max_level = 2
 
tagging.labels = velocity
 
tagging.velocity.type = FieldRefinement
tagging.velocity.field_name = velocity
tagging.velocity.grad_error = 0.001 0.001 0.001
velocity.max.level = 1
 
amr.n_cell = 16 16 32
----------------------------------------------------------------------------------------------------------------------------------------------

And there are some problems with it. It works only with this value of amr.n_cell. For example, if amr.n_cell = 16 16 16/32 32 64  -  it doesn't work. What is the reason for this?

**Comment by marchdf** [comment]
Hi, apologies for never addressing this issue. Were you able to resolve it? This can be due to a number of reasons and I would have to see the full input file to give a better answer.
