### ISSUE TITLE
Issue with actuator line model

### ISSUE THREAD

**Issue by AndreyBritov** [Exawind/amr-wind#554]
Hello!
I am trying to run NREL 5MW OpenFAST example, but have following error:
![Снимок экрана от 2022-01-21 17-28-10](https://user-images.githubusercontent.com/86724415/150543857-e65c1ca0-e25b-4c8f-a148-677060a43579.png)
For unknowing reasons, amr-wind don`t see the TurbineFastLine actuator.
Is it possible to compile it separately? Or maybe I am using old version without such kind of actuator model?
Thank you!

**Comment by sayerhs** [comment]
@AndreyBritov The actuator line model depends on [OpenFAST](https://github.com/openfast/openfast). The default CMake build of AMR-Wind doesn't link to OpenFAST. You will have to first compile OpenFAST and then configure and build AMR-Wind by asking it to link to AMR-Wind.

```
cmake -DAMR_WIND_ENABLE_OPENFAST=ON -DOPENFAST_DIR=<path_to_openfast_install>
```

**Comment by AndreyBritov** [comment]
Dear Sayerhs,
Thank you!
I have tried to do this:
![Снимок экрана от 2022-01-21 17-59-19](https://user-images.githubusercontent.com/86724415/150549268-e33c13a9-5be4-4149-8fcc-1fb05fd658ed.png)
But after building AMR-Wind with make, i got following errors:
![Снимок экрана от 2022-01-21 17-59-32](https://user-images.githubusercontent.com/86724415/150549369-63f22472-d3ae-498d-8f0b-1f0f69c20fe5.png)
And now i don`t know to do.
When I changed SC_ to SC_DX, i`ve got an issue with args in fast_func.

**Comment by AndreyBritov** [comment]
Hello!
Sorry for my long absent.
I`ve tried to change OpenFAST version, as you said
![Снимок экрана от 2022-01-26 13-38-18](https://user-images.githubusercontent.com/86724415/151148806-538f72f9-d8cd-4dc5-b180-109faf9e87fd.png)
But error has not disappeared. 
![Снимок экрана от 2022-01-26 13-38-32](https://user-images.githubusercontent.com/86724415/151148983-c9991650-ec56-40a2-9650-470a379cf94f.png)

**Comment by sayerhs** [comment]
@AndreyBritov The [SC header file](https://github.com/OpenFAST/openfast/blob/v2.6.0/modules/supercontroller/src/SuperController_Types.h#L23)  in OpenFAST v2.6.0 has the types that AMR-Wind is expecting. Can you confirm that what is installed and accessed by AMR-Wind during compilation time is indeed OpenFAST v2.6.0? 

For example, in OpenFAST install bin directory, if you execute the openfast executable does it report the version that you expect? 

You can also verify that the header file `SuperController_Types.h` in openfast install `include` directory matches with what is seen in Github.

**Comment by AndreyBritov** [comment]
Sayerhs, thank you for your reply!
When I am executing file in install bin directory, I have following situation:
![Снимок экрана от 2022-01-26 17-20-32](https://user-images.githubusercontent.com/86724415/151180103-3683fb56-1a1d-43f6-a09c-444523966a2d.png)
I don`t know, why instead of OpenFAST version there is written -HEAD-HASH-NOTFOUND

**Comment by AndreyBritov** [comment]
Dear Sayerhs,
Thank you, for your advice about cloning openfast directory from git!
I made it:
![Снимок экрана от 2022-01-31 14-55-08](https://user-images.githubusercontent.com/86724415/151789859-10cbadef-a067-4163-a636-348cf376d812.png)
But, actually, it`s bringing no results, issue the same:
![Снимок экрана от 2022-01-31 14-55-15](https://user-images.githubusercontent.com/86724415/151789957-e6de9ae7-8c81-4304-9c9e-85daac94d777.png)
![Снимок экрана от 2022-01-31 14-55-36](https://user-images.githubusercontent.com/86724415/151789971-04341da0-fd1a-4d33-b741-bcf4c0cce507.png)

**Comment by psakievich** [comment]
@AndreyBritov can you comment on this issue? I believe it should be resolved now.
