### ISSUE TITLE
Docs through github.io versus readthedocs.io

### ISSUE THREAD

**Issue by rybchuk** [Exawind/amr-wind#597]
AMR-Wind documentation can be found both at [https://exawind.github.io/amr-wind/](https://exawind.github.io/amr-wind/) and at [https://amr-wind.readthedocs.io/en/latest/](https://amr-wind.readthedocs.io/en/latest/). The banner on readthedocs.io says that it is the "latest" version of the documentation, but it is missing more recent documentation that can be found on the github.io page (e.g., [virtual lidar info](https://exawind.github.io/amr-wind/user/inputs_Sampling.html#sampling-along-a-line-moving-in-time-virtual-lidar)).

I'm unfamiliar with how the readthedocs.io page is run, but is it possible to sync the page to more recent updates? Or alternatively, can the banner there be updated to read something other than "latest"?

**Comment by jrood-nrel** [comment]
Thanks for reporting this. I've deleted the RTD page and removed the references to it since it was unintentional it still existed.
