### ISSUE TITLE
CMake building doesn't bring the entire regression test cases

### ISSUE THREAD

**Issue by yoonc5536** [Exawind/amr-wind#610]
Building AMR-Wind using CMake does not bring the entire test cases in the build directory. Particularly, latest test case, channel_mol_mesh_map_x, is not included in the build directory.

**Comment by jrood-nrel** [comment]
Those tests require hypre. Do you have hypre enabled?
https://github.com/Exawind/amr-wind/blob/19b0aeda8bacd5359de3ccb10de89e3c69875204/test/CMakeLists.txt#L220-L226

**Comment by yoonc5536** [comment]
Thank you for fast response. After installing HYPRE, I was able to have mesh mapping-related test cases.
