### ISSUE TITLE
First timestep for boundary planes varies with data format

### ISSUE THREAD

**Issue by rybchuk** [Exawind/amr-wind#611]
I ran into unexpected behavior when launching a turbine simulation using boundary plane data from a precursor simulation. I ran two more precursor simulations to investigate this behavior.

Let's say my precursor simulation has `time.fixed_dt = 1.0` and I set `ABL.bndry_output_start_time = 8999.0`. If I set the boundary output format to be netCDF `ABL.bndry_output_format = netcdf`, then the first value of `time` in `bndry_file.nc` is `8999`. If I set the boundary output format to be the default native format, then the first value of time in `time.dat` is `9000`. I've attached the two input files I used to test this behavior.

[abl_precursor_native.txt](https://github.com/Exawind/amr-wind/files/8542141/abl_precursor_native.txt)

[abl_precursor_netcdf.txt](https://github.com/Exawind/amr-wind/files/8542146/abl_precursor_netcdf.txt)

**Comment by tonyinme** [comment]
Hey @rybchuk , thanks for pointing this out. 

@michaeljbrazell , I am surprised that this does not show up in the [test](https://github.com/Exawind/amr-wind/blob/main/test/test_files/abl_bndry_input_native/abl_bndry_input_native.i).
Do you have any ideas?

**Comment by rybchuk** [comment]
@tonyinme, @michaeljbrazell helped me look into this issue. Turns out the tests were passing because `abl_bndry_output_native.i` started outputting data at `2.0` seconds (which is the 4th timestep), but `abl_bndry_input_native.i` used a restart file that started at the 5th timestep, which circumvents this issue. I'll submit a PR in just a second to resolve this.
