### ISSUE TITLE
HIP and CUDA backends failing unit test

### ISSUE THREAD

**Issue by afanfa** [Exawind/amr-wind#619]
Hello,
when using either the HIP or CUDA backend, the first unit test fails due to an illegal memory access; likely a CPU pointer is being read on the GPU or vice versa.
The problem started with commit: 9e008bb69837e7f02912ef191e138996d3280b5f . 
Is there a plan to fix this anytime soon?

**Comment by jrood-nrel** [comment]
Thanks for reporting this. It has showed up in our tests as well. https://my.cdash.org/test/55248308
