### ISSUE TITLE
Joukowsky disk `num_points_t` dependence

### ISSUE THREAD

**Issue by lawrenceccheung** [Exawind/amr-wind#632]
There might be an odd dependence of the Joukowsky disk forces and velocities on the value of `num_points_t`.  As you increase `num_points_t` (keeping everything else constant), the rotor disk velocity and actuator disk forces goes down monotonically:

![image](https://user-images.githubusercontent.com/15526007/173168792-e459790c-106a-4a29-8894-f7256ff42097.png)

FWIW, the averaged rotor velocity when `num_points_t=1` is closest to what I expect.

Looking at `Joukowksy_opts.H`, there might an extra division by `ddata.num_vel_pts_t` in the `grid.force` computation:  
https://github.com/Exawind/amr-wind/blob/8dea2fbab479a2c75d54c9b0b1e04021a1da7d21/amr-wind/wind_energy/actuator/disk/Joukowsky_ops.H#L207-L209

The area factor computation already accounts for a division by `ddata.num_vel_pts_t`:
```c++
        const amrex::Real dTheta =
            amr_wind::utils::two_pi() / ddata.num_vel_pts_t;

        const amrex::Real geometry_factor = ddata.dr * ddata.dr * dTheta * 0.5;
[..]
                const amrex::Real dArea =
                    geometry_factor * (std::pow(i + 1.0, 2) - std::pow(i, 2));
```

I can try removing the extra division to see if that fixes the problem.

Lawrence

**Comment by psakievich** [comment]
On it.  I'll add this fix in with the Cp computation.
