### ISSUE TITLE
Exception "CFL is below machine epsilon..."

### ISSUE THREAD

**Issue by mdorier** [Exawind/amr-wind#637]
(Sorry if posting an issue is not the right way to request help on AMR-WIND usage; I failed to find an alternate way)

I'm looking into AMR-WIND in the context of in situ analysis/visualization with Ascent. I'm not a physicist, so I don't know how to interpret the AMR-WIND input files. I've been provided with an input file that is supposed to run on a laptop, but when I run it, I'm getting this exception thrown:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  CFL is below machine epsilon and the time step is adaptive. Please use a fixed time step or fix the case setup
```

What is the way to solve this problem?

The input file is as follows:

```
#¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨#
#            SIMULATION STOP            #
#.......................................#
time.stop_time               =   10     # Max (simulated) time to evolve
time.max_step                =   100    # Max number of time steps
time.init_shrink = 0.001

#¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨#
# TIME STEP COMPUTATION #
#.......................................#
time.fixed_dt         =   -0.001        # Use this constant dt if > 0
time.cfl              =   0.8           # CFL factor
time.initial_dt = 0.001

#¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨#
# INPUT AND OUTPUT #
#.......................................#
io.KE_int = 0
io.line_plot_int = 5
#io.restart_file = chk00300
time.plot_interval            =  5       # Steps between plot files
time.checkpoint_interval      =  300     # Steps between checkpoint files
time.checkpoint_start         =  300

#¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨#
# PHYSICS #
#.......................................#
incflo.use_godunov = 1
incflo.godunov_type="weno"
transport.model = TwoPhaseTransport
transport.laminar_prandtl = 0.7
transport.turbulent_prandtl = 0.3333
turbulence.model = Laminar

incflo.physics = MultiPhase DamBreak
MultiPhase.density_fluid1=1000.
MultiPhase.density_fluid2=1.0
MultiPhase.verbose = 1
DamBreak.height=0.0571
DamBreak.width=0.0571
ICNS.source_terms = GravityForcing

#¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨#
# ADAPTIVE MESH REFINEMENT #
#.......................................#
amr.n_cell              = 80 16 24      # Grid cells at coarsest AMRlevel
amr.max_level           = 1             # Max AMR level in hierarchy
amr.max_grid_size      = 64
amr.blocking_factor     = 8
time.regrid_interval =  5
tagging.labels = TO1
tagging.TO1.type = InterfaceThicknessRefinement
tagging.labels = grad
tagging.grad.type = GradientMagRefinement
tagging.grad.field_name = density
tagging.grad.values = 10 10 10 10 10

#¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨#
# GEOMETRY #
#.......................................#
geometry.prob_lo = 0 0. 0. # Lo corner coordinates
geometry.prob_hi = 0.2855 0.0571 0.08565 # Hi corner coordinates
geometry.is_periodic = 0 1 0 # Periodicity x y z (0/1)

xlo.type = "slip_wall"
xhi.type = "slip_wall"
zlo.type = "slip_wall"
zhi.type = "slip_wall"

incflo.post_processing = ascent
ascent.type = Ascent
ascent.fields = velocity
ascent.output_frequency = 5
```

Also if you happen to have input file for scenarios requiring large-scale runs and producing visually interesting results with ascent, I would be very interested.

Thanks

**Comment by gdeskos** [comment]
Hmm, we have fixed this one in a local branch. I can do a quick PR with the fix later today

**Comment by mdorier** [comment]
I got the config to run by changing `time.fixed_dt` to `0.001` (instead of `-0.001`) but I don't know to what extent this is changing the physics of the simulation.

**Comment by psakievich** [comment]
@mdorier the error you are getting is just saying that the condition used to determine how big of a timestep the simulation can take (CFL) with adaptive time stepping is so small that it will make the calculation of the next timestep susceptible to precision errors.  By changing it to a positive number you are fixing the time step and avoiding this computation.

The physics should be fine. It is just that you are likely taking a smaller timestep than you need to, and thus making your simulation run for a longer time.

**Comment by mdorier** [comment]
@psakievich thanks for the explanation!
@gdeskos can you let me know when the fix is pushed? (or can you point me to the branch so I can integrate it on my local clone?)

**Comment by mbkuhn** [comment]
Hi @mdorier, this issue has now been fixed in the main branch of amr_wind. You should be able to run the dam_break case with an adaptive dt if you like. Furthermore, we have added significant improvements to the multiphase scheme within the code, so it is now mass- and momentum-conserving, as well as much more robust. Let us know if there are any further issues. I apologize that this took so long to be formally addressed.
