### ISSUE TITLE
Force points and velocity points are in different locations in ALM

### ISSUE THREAD

**Issue by tonyinme** [Exawind/amr-wind#673]
There are two locations of actuator points to store information in the ALM that gets passed to and from OpenFAST.
The velocities are sampled in one location and the forces are applied in another location.
In the case of very fine epsilons (epsilon/chord=0.25) this has a big impact in velocity sampling and loads (producing unrealistic results).
In simulations of the NREL 5MW, the code samples velocities that are often higher than the inflow throughout most of the blade.

The location of the velocity sampling should be the same as the force location for each actuator point (following standard ALM implementations). 

This issue has a minor impact when epsilon is big (epsilon/chord>>1), but has very strong impact when epsilon is small (epsilon/chord=0.25).

I have had discussions with some of you regarding this issue (tagged).
@mchurchf @psakievich @sayerhs @gdeskos 

I will also discuss with the OpenFAST team next week.

**Comment by tonyinme** [comment]
This bug is being addressed on the [OpenFAST side](https://github.com/OpenFAST/openfast/issues/1232).
We will require some code changes in amr-wind after the OpenFAST changes are implemented.

**Comment by andrew-platt** [comment]
The meshes have now been updated in the OpenFAST dev branch and will be included in the 3.4.0 release (https://github.com/OpenFAST/openfast/pull/1324).  See also issue https://github.com/OpenFAST/openfast/issues/1344.

**Comment by andrew-platt** [comment]
Also see https://github.com/OpenFAST/openfast/issues/1344 for mesh refinement in AeroDyn 15.

**Comment by tonyinme** [comment]
Bug was fixed in OpenFAST.
https://github.com/OpenFAST/openfast/pull/1324
