### ISSUE TITLE
Bugs in GeometryRefinement

### ISSUE THREAD

**Issue by psakievich** [Exawind/amr-wind#683]
I have noticed a few bugs with GeometryRefinement. For example if I do a cylinder refinement and change the outer radius from 5 to 1 it does not change my refinement region
```
tagging.static.min_level = 0
tagging.static.max_level = 2
tagging.static.type = GeometryRefinement
tagging.static.shapes = c1
tagging.static.c1.type = cylinder
tagging.static.c1.start = 0.0 0.0 -0.375
tagging.static.c1.end = 0.0 0.0 0.375
tagging.static.c1.inner_radius = 0.0
tagging.static.c1.outer_radius = 1.0
```
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/12102506/190504125-8cab90d8-91a5-4e4b-91c8-8ea3c065686a.png">

Using a box refinement my box is not being put in the correct location

```
tagging.static.shapes = b1
tagging.static.b1.type = box
tagging.static.b1.origin = -5.0 -5.0 -0.375
tagging.static.b1.xaxis = 10.0 0.0 0.0
tagging.static.b1.yaxis = 0.0 10.0 0.0
tagging.static.b1.zaxis = 0.0 0.0 0.75
```

The log file reports the box corners as 
```
  (-5 -5 -0.375)                                                                      
 (5 -5 -0.375)                                                                       
 (5 5 -0.375)                                                                        
 (-5 5 -0.375)                                                                       
 (-5 -5 0.375)                                                                       
 (5 -5 0.375)                                                                        
 (5 5 0.375)                                                                         
 (-5 5 0.375) 
 ```
 
 But the box is on the bottom of the domain and not centered (the domain extents are (-12,12), (-6,6) and (-0.375, 0.375) in the x,y and z directions respectively).  The white box in the image below outlines where the refinement box __should__ be.

<img width="1414" alt="image-2" src="https://user-images.githubusercontent.com/12102506/190504246-7027c6cb-1811-45f1-acda-fb7f11a5d4a9.png">

**Comment by lawrenceccheung** [comment]
Hi @psakievich, that's interesting.  I haven't had issues so far, but would you able to test out a case which previously worked?  I've been doing turbine cases with
```
# --- Geometry and Mesh ---
geometry.prob_lo                         = -2560.0 -960.0 -960.0
geometry.prob_hi                         = 2560.0 960.0 960.0  
amr.n_cell                               = 256 96 96           # Number of cells in x, y, and z directions
amr.max_level                            = 2                   
#---- tagging defs ----
tagging.labels                           = Farm_level_0_zone Farm_level_1_zone
tagging.Farm_level_0_zone.type           = GeometryRefinement  
tagging.Farm_level_0_zone.shapes         = Farm_level_0_zone   
tagging.Farm_level_0_zone.level          = 0                   
tagging.Farm_level_0_zone.Farm_level_0_zone.type = box                 
tagging.Farm_level_0_zone.Farm_level_0_zone.origin = -2400.0 -720.0 -480.0
tagging.Farm_level_0_zone.Farm_level_0_zone.xaxis = 4800.0 0.0 0.0      
tagging.Farm_level_0_zone.Farm_level_0_zone.yaxis = -0.0 1440.0 -0.0    
tagging.Farm_level_0_zone.Farm_level_0_zone.zaxis = 0.0 0.0 960.0       
tagging.Farm_level_1_zone.type           = GeometryRefinement  
tagging.Farm_level_1_zone.shapes         = Farm_level_1_zone   
tagging.Farm_level_1_zone.level          = 1                   
tagging.Farm_level_1_zone.Farm_level_1_zone.type = box                 
tagging.Farm_level_1_zone.Farm_level_1_zone.origin = -600.0 -600.0 -288.0
tagging.Farm_level_1_zone.Farm_level_1_zone.xaxis = 1200.0 0.0 0.0      
tagging.Farm_level_1_zone.Farm_level_1_zone.yaxis = -0.0 1200.0 -0.0    
tagging.Farm_level_1_zone.Farm_level_1_zone.zaxis = 0.0 0.0 576.0       
```
(see https://github.com/Exawind/wind-energy/blob/master/HFM_FY22Q4_ControlsBlockage/turbinecalibration/RunCalibration_IEA15MW_test.ipynb).  The refinement zones should look like:
![image](https://user-images.githubusercontent.com/15526007/190514047-63fc58a2-f8f3-435f-8db6-729036bea5aa.png)
and pretty much lines up with what I'm seeing in paraview:
![image](https://user-images.githubusercontent.com/15526007/190514075-90bd659a-f4c6-421e-8687-c4b372b31e8b.png)

Lawrence

**Comment by psakievich** [comment]
I can't seem to reproduce the box issues today.  Not sure what is going on at this point.

**Comment by michaeljbrazell** [comment]
@psakievich I think the gridding efficiency is too low. try this out: amr.grid_eff=1.0 at least for the cylinder.
