### ISSUE TITLE
How to estimate number of cells and optimal number of processors with static grid refinement

### ISSUE THREAD

**Issue by gantech** [Exawind/amr-wind#711]
For running wind turbine/farm simulations, we routinely create static grid refinement boxes of various kinds... cylinder/box/combinations. Is there an AMReX or some utility I can run without running the simulation that will tell me the total number of cells after refinement (after accounting for padding etc.) like shown in a typical output below?

I assume the optimal number of processors will also depend on the number of blocks and not just the total number of cells. So could we also get a utility to tell us the optimal number of processors or at least a good starting estimate?

```
Grid summary:
  Level 0   1024 grids  4194304 cells  100 % of domain
            smallest grid: 16 x 16 x 16  biggest grid: 16 x 16 x 16
  Level 1   756 grids  387072 cells  1.153564453 % of domain
            smallest grid: 8 x 8 x 8  biggest grid: 8 x 8 x 8
  Level 2   2000 grids  1996800 cells  0.7438659668 % of domain
            smallest grid: 8 x 8 x 8  biggest grid: 16 x 8 x 8
  Level 3   1539 grids  12441600 cells  0.5793571472 % of domain
            smallest grid: 24 x 16 x 16  biggest grid: 32 x 16 x 16
  Level 4   1280 grids  9961472 cells  0.05798339844 % of domain
            smallest grid: 24 x 16 x 16  biggest grid: 32 x 16 x 16```

**Comment by lawrenceccheung** [comment]
Hi @gantech,

You can use the [amr-wind frontend](https://github.com/Exawind/amr-wind-frontend) tool to estimate the mesh size given a set of static refinement zones.  We've used it before to help setup large cases and figure out how big of case we're dealing with.  For instance, in a previous HFM milestone I estimated the mesh in this notebook:
https://github.com/Exawind/wind-energy/blob/master/HFM_FY22Q4_ControlsBlockage/precursor/precursor1_5x5_tallrefined/precursor1_tallrefined.ipynb

If you already have a case in mind and a corresponding input file, you can use it in python like this  
```python
# Load the libraries
import amrwind_frontend as amrwind
# Start the case
case = amrwind.MyApp.init_nogui()
case.loadAMRWindInput('MYINPUTFILE.inp')
```
Then call the `estimateMeshSize()` function:
```python
# Estimate mesh size
case.estimateMeshSize()

Refinement box1: level 1: 3145728 cells
Refinement box2: level 2: 16777216 cells
Refinement box3: level 3: 50331648 cells
ESTIMATED MESH SIZE
   Level       Ncells                      Cell Size
       0       786432             80.0 x 80.0 x 80.0
       1      3145728             40.0 x 40.0 x 40.0
       2     16777216             20.0 x 20.0 x 20.0
       3     50331648             10.0 x 10.0 x 10.0
  TOTAL:     71041024
```
Of course, everything could be done through the GUI interface too.  Unfortunately the mesh estimator doesn't take into account the padding necessary for refinement zones, so this would basically be a lower bound estimate on the mesh size, but it should be accurate to within ~10%.

Lawrence

**Comment by marchdf** [comment]
Closing because I think @lawrenceccheung answered the question. Please reopen if not.
