### ISSUE TITLE
Improvement to FLLC in turbine case

### ISSUE THREAD

**Issue by tonyinme** [Exawind/amr-wind#726]
There was a bug in the filtered lifting line theory correction that has been addressed [here](https://github.com/Exawind/amr-wind/pull/725).
This has been fixed for the case of a fixed wing.

There are still some differences present in the case of a turbine coupled to openfast.
The correction works, but the magnitude of the correction is off when compared to a refined simulation with optimal values.

Been working with @psakievich on this.

This plot show the sampled velocity for a simulation with the NREL 5MW, 8m/s. 
We expect the values to be within less than 1% of each other at any location.

![image](https://user-images.githubusercontent.com/11055361/202826191-e2e5fc92-fbfb-4254-a99c-2e65c01a5b7a.png)

**Comment by psakievich** [comment]
@tonyinme this plot is interesting. Would you comment on the temporal convergence of the profiles in these cases?  More of a sanity check since the relaxation factor for the FLLC is pretty heavy.  Are we sure the runtime and averaging is sufficient for both cases to give a converged result?

**Comment by tonyinme** [comment]
Thanks @psakievich , that's a good point about the relaxation. 
Yes, the simulations are converged. They run for 200 seconds.

**Comment by tonyinme** [comment]
This was caused by the velocity sampling in the ALM. 
This was fixed by updating the velocity sampling here.
https://github.com/Exawind/amr-wind/pull/868
