### ISSUE TITLE
Crash with CoriolisForcing and GeostrophicForcing

### ISSUE THREAD

**Issue by rybchuk** [Exawind/amr-wind#731]
I am trying to run a simulation that uses both `CoriolisForcing` and `GeostrophicForcing`, but I immediately ran into an unexpected crash and error.

```
Creating MomentumSource instance: BoussinesqBuoyancy
Creating MomentumSource instance: CoriolisForcing
Geostrophic forcing: Coriolis factor = 0.0001454441043
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Assertion `amrex::Math::abs(latitude - 90.0) < static_cast<amrex::Real>(vs::DTraits<float>::eps())' failed, file "/projects/awaken/orybchuk/spack-june22/amr-wind/amr-wind/equation_systems/icns/source_terms/GeostrophicForcing.cpp", line 41
``` 

I am trying to run this simulation with a value of `CoriolisForcing.latitude = 45.0`. Notably, I found that this error goes away if...
* I instead use `CoriolisForcing.latitude = 90.0`, or
* I use `ABLForcing` instead of `GeostrophicForcing`, which is weird, because I wouldn't expect either of these to directly impact `CoriolisForcing`

I am using the version of the code at `12610773efd2f80bd34a74d5e979af012c5c6d98`. 

I've attached the input file as well as the full error file.
[job_output_filename.10846802.txt](https://github.com/Exawind/amr-wind/files/10072268/job_output_filename.10846802.txt)
[abl_spinup.txt](https://github.com/Exawind/amr-wind/files/10072269/abl_spinup.txt)

**Comment by michaeljbrazell** [comment]
@gdeskos is working with Jarred to fix this here: https://github.com/Exawind/amr-wind/pull/665

**Comment by marchdf** [comment]
@gdeskos and @rybchuk what is the status of this problem? Looks like there was a PR but one that did not get merged?

**Comment by mbkuhn** [comment]
wondering if this merged PR has successfully addressed the issue? #897

**Comment by rybchuk** [comment]
I've just been running all my geostrophic simulations at 90 degrees since opening this issue. I think Georgios would have a better sense on if a fix was implemented or not

**Comment by gdeskos** [comment]
Should be fixed! @rybchuk can you run a sim with 2d forcing set to true and then instead of 90 degrees you use your actual latitude but keep Earth's rotation to its actual value to get the same effect?

**Comment by rybchuk** [comment]
@gdeskos Maybe, I'm not sure how the math works out haha. My geostrophic simulations have all been idealized though, sot he specific choice of latitude in these simulations hasn't actually been critical. It's just common convention to use a midlatitude value instead of 90
