### ISSUE TITLE
Discontinuities in sampled velocities passed to OpenFAST on first time-step

### ISSUE THREAD

**Issue by tonyinme** [Exawind/amr-wind#750]
When running a simulation using OpenFAST and ALM, there is a problem with the velocities being passed to openfast.
This is a one-blade turbine simulation (fixed wing) that we are using to debug.
These [velocities](https://github.com/Exawind/amr-wind/blob/a409c5af9cabc27b934dca7d63f4632b47a5701f/amr-wind/wind_energy/actuator/turbine/fast/turbine_fast_ops.H#L390) have a problem shown in the file below.
On the very first time-step, these velocities should all match the initial condition (1 everywhere).

This issue not seem to depend on number of cores and can be reproduced with only 1 core. 

![image](https://user-images.githubusercontent.com/11055361/206808538-7517ff5e-de25-4d20-8058-5d0cae32376b.png)

**Comment by tonyinme** [comment]
Following up on our conversation with @psakievich @lawrenceccheung @michaelasprague , here are the input files for a case with less number of actuator points (60) and coarser epsilon (epsilon/R=.1). The same issue is still present even when using less actuator points.

[amr_wind_nrel5mw_fixed_wing_coarse.zip](https://github.com/Exawind/amr-wind/files/10997075/amr_wind_nrel5mw_fixed_wing_coarse.zip)

![image](https://user-images.githubusercontent.com/11055361/225790604-9bd3dfa0-792c-42f2-bcc7-f98d5394f7cf.png)

**Comment by tonyinme** [comment]
Hi @marchdf , yes, this is still an issue. It only happens for the first time-step, so it is not stopping our simulations from running or affecting the results after some time.

**Comment by mbkuhn** [comment]
> Hi @marchdf , yes, this is still an issue. It only happens for the first time-step, so it is not stopping our simulations from running or affecting the results after some time.

Do you know if this is an issue upon restart?

**Comment by tonyinme** [comment]
That's a good question. I haven't checked restarting. I see it in the
beginning of a simulation.

**Comment by tonyinme** [comment]
@mbkuhn , I tried running a restart simulation with the test above and I can confirm that this only shows up in the very first time-step of a new simulation. When restarting the simulation, we do not see the same problem.
