### ISSUE TITLE
Documentation for actuator disk models in AMR wind

### ISSUE THREAD

**Issue by genevievestarke** [Exawind/amr-wind#753]
Hi!
I'm looking to run a simulation in AMR wind with actuator disks, but I can't find documentation of the inputs for these models.

**Comment by lawrenceccheung** [comment]
Hi @genevievestarke, are there any particular types of actuator disks that you're interested in running?  We can set up actuator disks with OpenFAST models, uniformly loaded actuator disks, or Joukowski model actuator disks (the latter two are OpenFAST independent).  We could probably use more documentation on all three, but let me know if there's interest in a particular type.

Lawrence

**Comment by genevievestarke** [comment]
Hi @lawrenceccheung, I think documentation on the uniformly loaded actuator disks first would help the most.  Thank you!

**Comment by rybchuk** [comment]
Hi @genevievestarke, I just stumbled across this issue. I set up a practice run a while back for a neutral ABL with three [turbines](https://github.com/NREL/openfast-turbine-models/tree/master/IEA-scaled/NREL-2.8-127/OpenFAST). It uses actuator lines, but this hopefully helps.
1. First run the precursor
2. Run `calc_inflow_stats.py` on your precursor `post_processing/` files, corresponding to your upcoming turbine simulation period (e.g., 9000-10800 sec) to calculate forcing to mimic `ABLForcing`
3. Run the turbine simulation

Please let me know if these files don't work out of the box or if anything looks funny.

[three_turb_demo.zip](https://github.com/Exawind/amr-wind/files/10316333/three_turb_demo.zip)
