### ISSUE TITLE
Oom-kill event when writing plotfiles

### ISSUE THREAD

**Issue by rybchuk** [Exawind/amr-wind#765]
I am running a large simulation, (nx,ny,nz) = (2560, 1536, 256), and I hit this error when trying to save a plotfile:

```
Begin initial pressure iterations. Num. iters = 3
dt: 0.5
CFL: 0.497796 (conv: 0.497796 diff: 0 src: 0 )

Godunov:
  System                     Iters	Initial residual        Final residual
  ----------------------------------------------------------------------------
  MAC_projection                12         0.00870306381       1.108326264e-14
  temperature_solve              3         0.09375444689        1.68824954e-11
  tke_solve                      3	 0.0002059373344       2.964295476e-14
  velocity_solve                 3         0.06404867034       2.847166079e-11
  Nodal_projection               7         0.03469062469       1.563280755e-13

...

Writing plot file	plt00000 at time 0

HDF5 plotfile using ZFP_ACCURACY, 0.001, 1024
slurmstepd: error: Detected 8407 oom-kill event(s) in StepId=11243758.0. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: r104u33: task 48: Out Of Memory
slurmstepd: error: Detected 5962 oom-kill event(s) in StepId=11243758.0. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

In this particular instance, I hit the error at time=0 and with the HDF5 data format. This simulation was run using 2 nodes (72 cores). I ran into the error for a similarly sized simulation at a later timestamp (~30 min) using the native AMReX data format and 32 cores (1152 nodes).

Do you have a sense of why this issue popped up and how to resolve it? I've attached the configuration file for reference. Thanks!

[abl_precursor.txt](https://github.com/Exawind/amr-wind/files/10300595/abl_precursor.txt)

**Comment by jrood-nrel** [comment]
Is it your intention to use HDF5 with compression? I've been finding it to only work as intended in certain circumstances, i.e. small simulations.

**Comment by rybchuk** [comment]
It is, yes. I have experience doing TB-scale analysis on HDF5 files, so I was hoping to work with data in that format over the AMReX format. 

I ran into a similar but distinct error when I tried running the same simulation with AMReX output, but when I doubled the number of nodes, the AMReX output simulation ran correctly. I haven't had a chance to test the HDF5 output with the same number of nodes yet, but I'm optimistic that will work.

**Comment by jrood-nrel** [comment]
Excellent. Let me know if it works. I guess I should mention my HDF5 ZFP experience where it doesn't work is coming from another AMReX code I work on, but I haven't had a chance to use HDF5 much in AMR-Wind yet. So that is an assumption on my part.

**Comment by rybchuk** [comment]
Quick update on my end: I ran the same simulation but with 64 nodes (which solved the AMReX format issue I had), but I hit the same oom error for HDF5.

**Comment by marchdf** [comment]
Sounds like this was resolved given the last comment. @rybchuk is this still an issue? If not, feel free to close.
