### ISSUE TITLE
Saved temperature BC from precursor not transferring correctly to inflow-outflow

### ISSUE THREAD

**Issue by rthedin** [Exawind/amr-wind#782]
When using precursor boundary data onto an inflow-outflow case, the temperature field is transferred with an offset of about 60 K. This results in very nonphysical results due to the sharp temperature gradient that develops within the first couple of seconds of simulation time.

I put together very simple reproducible cases-- attached here. They are not _exact_ copies of the regression tests, but they are  lightly modified [abl_bndry_input_amr_native](https://github.com/Exawind/amr-wind/tree/main/test/test_files/abl_bndry_input_amr_native) and [abl_bndry_output_native](https://github.com/Exawind/amr-wind/blob/e0ffbb62eb60d70d74b02ed2a2587551face2aa2/test/test_files/abl_bndry_output_native/abl_bndry_output_native.inp). The entries on the input files are in the same order to allow a quick `vimdiff`.

The issue occurs with either `native` or `netcdf` boundary format. Executed using 7ca092e9b07a13e2ee5c984a06d6629c2197097f.

Here's a snapshot of the issue, being `xlo` the only inflow plane:
![image](https://user-images.githubusercontent.com/13243358/217100476-cda0abd7-39c6-456e-8f01-db5bff6d4258.png)

[setup_precursor_neutral.i.txt](https://github.com/Exawind/amr-wind/files/10669680/setup_precursor_neutral.i.txt)
[setup_turbine_neutral.i.txt](https://github.com/Exawind/amr-wind/files/10669682/setup_turbine_neutral.i.txt)

**Comment by michaeljbrazell** [comment]
I wonder if this is due to density not being 1.0?

**Comment by rthedin** [comment]
Density 1 fixes it. I will try on a more realistic case that I was having issues with and will report back. Is it a requirement that `incflo.density` be always 1?

**Comment by michaeljbrazell** [comment]
it shouldn't be a requirement... somehow we missed this one

**Comment by lawrenceccheung** [comment]
@rthedin, in your `setup_turbine_neutral.i` input file, try changing
```
xlo.density = 1.0
```
to
```
xlo.density = 1.225
```
to match the original density in the precursor.  Basically 300/1.225 = 244.9, which is close the BC inflow values you're seeing.  In my cases I've always matched my `xlo` density, just in case...

Lawrence

**Comment by rthedin** [comment]
Lawrence and Mike, that was it. I had inconsistent densities on my cases. At some point I had `incflo.density` set correctly, but not `xlo.density`. That went totally overlooked by me with my overwhelmingly large input file with turbines and refinements. Thank you for the tip!

**Comment by marchdf** [comment]
Is there any way we can guard against this? A check that `incflo.density == xlo.density`? But I can see many issues with that as well...

**Comment by rthedin** [comment]
I think that would be a really nice check. Not just `xlo` but also `ylo` if that is also an inflow plane. And I would say maybe encourage users to setup their inflow-outflow case starting with a copy of their precursor case? I had many input files that I was "merging together" based on what other people gave me, and I definitely did not start with a copy of the precursor. That is what I will be doing from here on.

**Comment by psakievich** [comment]
@marchdf maybe we can add an option `amr_wind.consistent_density` that we default to true?  That can enforce these checks, but it provides a way to turn it off if necessary.

**Comment by marchdf** [comment]
@psakievich that might be a good idea. I was leaning towards a "warning" but that might be easy to overlook... Let me see if I can mock something up.

**Comment by lawrenceccheung** [comment]
@rthedin, restarting a precursor case to include inflow/outflow is actually a pretty involved process, and it's easy to forget one of the steps.  This is a list of everything that needs to be done to ensure proper consistency:

```
1.	Set bndry_io_mode=1
2.	Set ABL.bndry_file to point to the boundary file/directory
3.	Change the periodicity arguments on x/y planes
4.	Set the inflow planes on x/y boundaries to mass inflow (include correct density).
5.	Set the outflow planes on x/y boundaries to pressure outflow
6.	Set the body force
        a.	Add BodyForce to ICNS.source_terms
        b.	Calculate the horizontal forcing from the ablstats file (averaged over a period of time)
        c.	Add that body forcing to BodyForce.magnitude
7.	Turn off ABL forcing (remove it from ICNS.source_terms)
8.	Add ABLMeanBoussinesq in ICNS.source_terms
9.	Set ABL.wall_shear_stress_type to local (Matt might be working on this, the actual wall model might change in the near future)
```

You are correct that we should always start with the precursor case when configuring the restart, however, it's easy to forget skip steps 6 or 9, for instance.  I've got some code in the amr-wind-frontend to automate this process, and to automatically figure out what `xlo.density` to use -- you can see an example of how it works [here](https://github.com/lawrenceccheung/AWAKEN_summit_setup/blob/main/UnstableABL_farmrun1/FarmRun1.ipynb).  

Lawrence

**Comment by marchdf** [comment]
@lawrenceccheung yikes... maybe we need to document that bullet list in the docs? 

@psakievich I like that idea. Default everything to `icns.density` and then let the user overwrite. Given the number of decks out there already I still like adding an extra guard rail to ensure that the densities are intentionally set to be different.

**Comment by lawrenceccheung** [comment]
@marchdf I completely agree.  I just realized there's an [open PR #553](https://github.com/Exawind/amr-wind/pull/553) regarding the documentation of the inflow-outflow capability.  Let me work with @neilmatula on this to make sure it's properly documented.
