### ISSUE TITLE
ABL physics wall_model at zhi is using the wrong zref

### ISSUE THREAD

**Issue by moprak-nrel** [Exawind/amr-wind#803]
Currently for the MO-law there seems to be just one zref, which is either input file specified or the first cell height from the bottom. When the wall model option is specified for zhi, it seems to use the same bottom zref at the top too, which is incorrect.

**Comment by marchdf** [comment]
@moprak-nrel was this addressed by my zhi fix? Or is that different?

**Comment by moprak-nrel** [comment]
Part of this issue is that there is only one `zref`, which is then used to populate the `MOData`, where `utau` is computed as https://github.com/Exawind/amr-wind/blob/10cd537c708f5bb1472a6664193fcda5a661910d/amr-wind/wind_energy/MOData.cpp#L45 
Currently `zref` is specified at the bottom wall, and hence the `utau` corresponds to `zlo`. However, this same `utau` is used in the shear stress calculations for `zhi` at https://github.com/Exawind/amr-wind/blob/10cd537c708f5bb1472a6664193fcda5a661910d/amr-wind/wind_energy/ABLWallFunction.cpp#L156
I'm not entirely sure what a simple fix for this would look like. I am also curious about which ABL contexts require a MO type model at `zhi`.

**Comment by moprak-nrel** [comment]
Should we just got rid of the `zhi` wall model option for ABLs? The fix is non-trivial and it's unclear if a MO model is needed at the top at all.

**Comment by hgopalan** [comment]
MO model provides lower wall boundary condition for the atmospheric boundary layer simulations. It cannot be used at the top of the domain as a boundary condition as it will be invalid. It might be better to remove this feature.
