### ISSUE TITLE
How to couple AMR-WIND with OpenFAST

### ISSUE THREAD

**Issue by calcin** [Exawind/amr-wind#855]
Dear all,

How about amr-wind coupling with openfast? I am a beginner, where should I go to find some AMR-WIND tutorial materials?
Any help would be appreciated,

Best regards,

**Comment by tonyinme** [comment]
Hi @calcin , thanks for pointing this out.
The [amr-wind frontend](https://github.com/Exawind/amr-wind-frontend/tree/main) should also have some examples available.

@lawrenceccheung and @psakievich , I believe the ADM capability is in the code but we don't have any documentation for the ADM, just for the ALM.

[Docs](https://exawind.github.io/amr-wind/user/inputs_Actuator.html#turbinefastline)
