### ISSUE TITLE
GPU: Loading an ABL broken on Frontier

### ISSUE THREAD

**Issue by PaulMullowney** [Exawind/amr-wind#856]
I am running a case of Exawind with a single turbine and an abl loaded from file.

This is on Frontier. 

The CPU version appears to run correctly.  The GPU version fails in the first amd-wind time step. 

Nalu looks nearly identical between cpu and gpu in the first time step.
 
The example is in the 1_turb_abl subdir at:
git@github.com:Exawind/exawind-cases.git

**CPU shows:**
==============================================================================
Step: 30001 dt: 0.003443526171 Time: 15000 to 15000.00344
CFL: 0.0657837 (conv: 0.0657837 diff: 0 src: 0 )
For mflux_type, default is upwind

Godunov:
  System                     Iters      Initial residual        Final residual
  ----------------------------------------------------------------------------
MLMG: Initial rhs               = 6.431129131
MLMG: Initial residual (resid0) = 6.431129131
MLMG: Final Iter. 6 resid, resid/bnorm = 2.734340926e-06, 4.251727606e-07
**MLMG: Timers: Solve = 1.411298605 Iter = 1.397386763 Bottom = 1.111773512
  MAC_projection                 6           6.431129131       2.734340926e-06**
MLMG: Initial rhs               = 311.1982457
MLMG: Initial residual (resid0) = 3.882800922e-05
MLMG: Final Iter. 2 resid, resid/bnorm = 3.456079867e-11, 1.11057177e-13
MLMG: Timers: Solve = 0.146567733 Iter = 0.115391598 Bottom = 0
  temperature_solve              2       3.882800922e-05       3.456079867e-11
  
**GPU shows:**

==============================================================================
Step: 30001 dt: 0.003443526171 Time: 15000 to 15000.00344
CFL: 0.0657837 (conv: 0.0657837 diff: 0 src: 0 )
For mflux_type, default is upwind

Godunov:
  System                     Iters      Initial residual        Final residual
  ----------------------------------------------------------------------------
MLMG: Initial rhs               = 6.431129131
MLMG: Initial residual (resid0) = 6.431129131
**MLMG: Timers: Solve = 15.27627675 Iter = 15.26372568 Bottom = 4.575246976
  MAC_projection               200           6.431129131          0.0918438591**
MLMG: Initial rhs               = 311.1982479
MLMG: Initial residual (resid0) = 1.725899426e-05
MLMG: Final Iter. 1 resid, resid/bnorm = 0, 0
MLMG: Timers: Solve = 0.076025352 Iter = 0.056321229 Bottom = 0
  temperature_solve              1       1.725899426e-05                     0

**Comment by marchdf** [comment]
Is this still an issue? I've been running ABL restarts with amr-wind on frontier and haven't seen this problem yet.
