### ISSUE TITLE
Feature Request: Start time for sampling 

### ISSUE THREAD

**Issue by abhineet-gupta** [Exawind/amr-wind#863]
It would be a useful feature to add a start time for when saving the sampling data is initiated. A significant amount of simulation is usually discarded for initialization and saving sampling info for that that period by default creates huge sampling files which require more memory and cpu time to process.

**Comment by mbkuhn** [comment]
Addressing this by having a delay (in timesteps) before sampling begins. Using timesteps because the sampling output frequency is in timesteps. In the future, a time-based output frequency and delay could be added, similar to recent plot and checkpoint improvements.
