### ISSUE TITLE
Power underestimated by OpenFAST using ALM in AMR-Wind

### ISSUE THREAD

**Issue by wenchaoyu** [Exawind/amr-wind#869]
Dear all, 

Recently, I encounted an issue when running AMR-Wind with OpenFAST using actuator line method for a single NREL5MW turbine in a uniform inflow 8 m/s, the generator power predicted is close to 1MW in this simulation while the reference value is [1.77MW](https://github.com/NREL/turbine-models/blob/master/Offshore/NREL_5MW_126_RWT.csv). We tried to use different epsilon values in actuator line method, we observed the power increased slightly as a function of epsilon, but still away from 1.77MW (shown in the figure below)
![image](https://github.com/Exawind/amr-wind/assets/4232919/5654088e-23bf-47a6-b5b9-114fa05f15ca)

Another issue we saw is the tower cannot be seen through the actuator source term, so the flow is not disturbed by the presence of tower even we have 50 forcing points on the tower
![image](https://github.com/Exawind/amr-wind/assets/4232919/d5161a23-9c8e-4ddd-a83d-99021d4b7d7b)

I would like to see if you have seen these kinds of issues before? Would it be something I wrongly configurated in AMR-Wind or OpenFAST input files? 

Thank you for any comments.
Best regards

AMR-Wind:  main version dated to 20230620
OpenFAST version: v3.4.1 and v3.5.0

**Comment by tonyinme** [comment]
Hi @wenchaoyu , can you please share the input files for the simulation and for the openfast turbine (.fst, elastodyn, and aerodyn input files)?

**Comment by wenchaoyu** [comment]
Hi @tonyinme, thank you for your reply. Please find here all the input files, and feel free if you need more informations. 
[NREL5MW_AMRWind.tar.gz](https://github.com/Exawind/amr-wind/files/11918136/NREL5MW_AMRWind.tar.gz)

**Comment by tonyinme** [comment]
Hi @wenchaoyu , when running openfast with CFD (ALM), you need to setup this flag in aeroyn to zero.

`          1   WakeMod            - Type of wake/induction model (switch) {0=none, 1=BEMT, 2=DBEMT, 3=OLAF} [WakeMod cannot be 2 or 3 when linearizing]
`

I will close this issue for now.
Let us know if this fixes the problem or if we need to reopen the issue.

**Comment by wenchaoyu** [comment]
Hi @tonyinme, thank you for this information.
To confirm with you, it helps to resolve the issue on the power underestimation, now we can get the power very close to the reference power.

However, the tower is still not shown via the actuator source term, only the blade can be seen. Since we would like to investigate on the effect of the tower, it is important to make sure it is taken into account in ALM. Can you confirm if it is the case on your side? If not, am I missing some other flags in aerodyn regarding tower? (I tried some of them, but none of them can help to get the tower back.

Thanks for your help.

**Comment by tonyinme** [comment]
Hi @wenchaoyu , 
Have you checked the simulations in detail?
The tower produces a small drag force, compared to the higher lift force from blades.
Can you check your simulations and adjust the ranges of the forces being plotted to make sure that the tower forces are there or not?
Also, can you try setting the number of tower points in the amr-wind input file to the same as openfast?

`         12   NumTwrNds         - Number of tower nodes used in the analysis  (-) [used only when TwrPotent/=0, TwrShadow/=0, TwrAero=True, or Buoyancy=True]
`

**Comment by wenchaoyu** [comment]
Hi @tonyinme, 

Yes, I tried to set the number of tower points in amr-wind `Actuator.TurbineFastLine.num_points_tower = 12`, but still cannot see the tower via actuator source term, no matter how I adjusted the ranges of the forces being plotted (see figure below)
![image](https://github.com/Exawind/amr-wind/assets/4232919/792ad2c0-8508-4936-bb04-3239fed960a5)

and the wind speed seems not to be affected by the tower in this simulation with uniform inflow:
![image](https://github.com/Exawind/amr-wind/assets/4232919/ed210f50-6864-4b0c-a509-a5cece4239bc)


And I ask this question since the tower can be seen in my naluwind simulation via actuator source term with right ranges of forces:
![image](https://github.com/Exawind/amr-wind/assets/4232919/ec360697-777b-4773-9d3d-27579f490671)

**Comment by tonyinme** [comment]
Yes, it can. Make sure that the number of tower points is the same in
openfast and amr-wind.
