### ISSUE TITLE
AMR-Wind_OpenFAST-ROSCO

### ISSUE THREAD

**Issue by AsimUdel** [Exawind/amr-wind#981]
Hello,
I am Asim from the University of Delaware. I am having a problem running wind turbine simulation in the AMR-Wind: my simulations terminate with a certain error; I am attaching my log output file in the attachment. One other thing I have compiled OpenFAST with  - Compiler: Intel(R) Fortran Compiler for applications running on Intel(R) 64, Version 2023.0.0 Build 20221201 instead of Compiler: GCC version 7.2.0, is it the main cause of the problem I am facing? Thank you
[logout.txt](https://github.com/Exawind/amr-wind/files/14375538/logout.txt)

**Comment by rybchuk** [comment]
Hi Asim, these specific lines
```
  >> A fatal error occurred when parsing data from "NREL_turbines/NREL-2p8-127_AeroDyn15.dat".
  >> The variable "Buoyancy" was not found on line #13. 
```

make me think that the `.dat` OpenFAST file that you're using is different than the version of OpenFAST that is in your AMR-Wind file. Lawrence has some nice documentation on modifying the OpenFAST files to go between a few specific versions [here](https://github.com/lawrenceccheung/amrwind-frontend/blob/afbc1dd284095ee869ba8a9cd3760fdf8b08ca82/docs/openfast_turbine.md). I recommend trying to compile AMR-Wind with OpenFAST version 3.4.1 . I think that'll solve things, but if not, try compiling with OpenFAST version 3.1.0

**Comment by AsimUdel** [comment]
Hi Alex,
Thank you so much. I had followed Lawrence's guide for the changes in the
OpenFAST files. had compiled OpenFAST v3.4.1 and also 3.0.0, but the
problem was still there. I will try compiling v3.1.0 too and give it a try.
Best wishes
Asim








*Asim Feroz*
Ph.D. Student
Mechanical Engineering Department
University of Delaware
Cell: +1-302-784-9053

**Comment by rybchuk** [comment]
Hi @AsimUdel, I wanted to check in: were you able to resolve the OpenFAST issue?

**Comment by AsimUdel** [comment]
Hi Alex, Thank you for checking, Yes, I was able to solve the OenFAST issue and ran with only 5 MW NREL no servo wind turbine although I have come across errors in other wind turbine models files. So I wanted to ask you that I compiled the OpenFAST with Intel compiler but in here (https://github.com/lawrenceccheung/amrwind-frontend/blob/afbc1dd284095ee869ba8a9cd3760fdf8b08ca82/docs/openfast_turbine.md#going-from-openfast-v26-to-v300) it is compiled with GCC, can this cause any problem?

**Comment by rybchuk** [comment]
Great to hear that you found a fix!

If you compiled OpenFAST with Intel, then be sure to compile AMR-Wind with Intel. I think Lawrence and I have been compiling with gcc for the sake of convenience (though at NREL at least, we're starting to use Intel more often because of our new supercomputer).

**Comment by AsimUdel** [comment]
Okay sure, I will try to compile OpenFAST with the same compiler as of AMR-Wind and will run simulation on that and will see that if there is any problem. Thank you

**Comment by mbkuhn** [comment]
Well done, @rybchuk. Thank you, @AsimUdel for using the issues page!
