### ISSUE TITLE
Unable to see variable in (Netcdf file)

### ISSUE THREAD

**Issue by AsimUdel** [Exawind/amr-wind#991]
Hello,
I am having trouble in reading the variables in my output file (.nc) (sampling00000.nc) file when I try to open in Python Jupyter notebook but I am able to read and see in AMR-Wind-Frontend (GUI), could someone please tell me what I should change in my input file so that I could see variables using Python or how to visualize the output file with some other tools? I am attaching my input file here in the attachment. Thank you 
[AMR-Wind_input_file.txt](https://github.com/Exawind/amr-wind/files/14529730/AMR-Wind_input_file.txt)

**Comment by lawrenceccheung** [comment]
Hi @AsimUdel 

There shouldn't be any changes you need to make to the AMR-Wind input file itself.  The sampling output files should be viewable in any environment that can load netcdf files, and if you can view them through the amr-wind-frontend GUI, then it ought to be possible to plot them in a jupyter notebook.

One thing that you can try is using a notebook like this one to visualize the `sampling00000.nc`: 
https://github.com/lawrenceccheung/ALCC_Frontier_WindFarm/blob/main/precursor/MedWS_LowTI/postprocessing/HubHeight_Viz.ipynb
This one might be a little more lightweight notebook, and doesn't require loading the full amr-wind-frontend library in order for it to work.  

Let me know if you have any questions about how to use it, or if you run into any issues loading it.

Lawrence

**Comment by AsimUdel** [comment]
Hi @lawrenceccheung 
Thank you so much, I have tried opening in Python using Jupyter notebook, I have come up with some error, Let me attach the file containing error, maybe I am doing something w
[error_while_opening_netcdf_file.txt](https://github.com/Exawind/amr-wind/files/14547623/error_while_opening_netcdf_file.txt)
rong. I would be grateful if you could guide me how to use https://github.com/lawrenceccheung/ALCC_Frontier_WindFarm/blob/main/precursor/MedWS_LowTI/postprocessing/HubHeight_Viz.ipynb this file.

**Comment by lawrenceccheung** [comment]
Hi @AsimUdel,

In the part of your script where you calculate the horizontal velocity
```python
>>> iplane=1
>>> Uh=np.sqrt(db['velocityx'][0][iplane,:,:]**2)
```
set `iplane=0`.  You only have one plane defined for `xyplane`, so that's why this error message appears:
```python
IndexError: index 1 is out of bounds for axis 0 with size 1
```

Note that you have both the `xyplane` and `yz` contained in `sampling00000.nc`.  By default, `getPlaneXY()` will extract the first plane that it sees (`xyplane`).  To get the other plane, use the `groupname` option:
```python
db     = ppsamplexr.getPlaneXR(amrdir+ncfile, iters, varnames, groupname='yz', verbose=0)
```

Lawrence

**Comment by rybchuk** [comment]
If you're using `xarray`, you will often have to specify the `group` variable when running `xr.open_dataset`. Below I've attached a screenshot of some code where I ran 6 different spinup simulations (I was trying different roughness and surface flux heat values), and you can see how I open the netCDF data of each of those simulations and concatenate them. I end up with two Datasets in the end: one for the profile variables (`pstats`) and one for the other variables.

![image](https://github.com/Exawind/amr-wind/assets/8021012/714d3794-e385-4b4d-bc96-4d750782da10)

**Comment by lawrenceccheung** [comment]
hi @AsimUdel, in your case use
```python
Uh = np.sqrt(db['velocityx'][2][iplane,:,:]**2)
```
In that last cell.

The dictionary that is returned by `ppsamplexr.getPlaneXR()` has the following structure:
```python
db[varkey][iterkey][planenum, i, j]
```
where:
- `varkey` corresponds to the variable name (in your case `velocityx`)
- `iterkey` corresponds to the time instance of the plane.  In your case, you only extracted the slice corresponding `iterkey`=2 because you specified `iters=[2]` above.
- `planenum` is the offset plane number of the sample plane.  In all cases you will have `planenum=0` present, and if in the input file you provide.  If you used the `offsets` specification in the input file, like in this example:
```
turbswA_.T0_swA.type                     = PlaneSampler        
turbswA_.T0_swA.num_points               = 601 45              
turbswA_.T0_swA.origin                   = 730.0 2560.0 0.08400000000000318
turbswA_.T0_swA.axis1                    = 3810.0 0.0 0.0      
turbswA_.T0_swA.axis2                    = 0.0 0.0 280.416     
turbswA_.T0_swA.normal                   = -0.0 1.0 -0.0       
turbswA_.T0_swA.offsets                  = 0.0 254.0 508.0     
```
you can specify `planenum`=1 or 2 as well.
- `i` and `j` are the x and y indices of the plane that will be used to plot.

Hope this helps.

Lawrence

**Comment by AsimUdel** [comment]
@lawrenceccheung 
Thank you so much for comprehensive guide, right now I have plotted it. 
![new_amr](https://github.com/Exawind/amr-wind/assets/156853074/c029f826-4c37-4a87-9872-0e6a3981b2b4)

**Comment by AsimUdel** [comment]
> If you're using `xarray`, you will often have to specify the `group` variable when running `xr.open_dataset`. Below I've attached a screenshot of some code where I ran 6 different spinup simulations (I was trying different roughness and surface flux heat values), and you can see how I open the netCDF data of each of those simulations and concatenate them. I end up with two Datasets in the end: one for the profile variables (`pstats`) and one for the other variables.
> 
> ![image](https://private-user-images.githubusercontent.com/8021012/311750444-714d3794-e385-4b4d-bc96-4d750782da10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjgxNDcsIm5iZiI6MTcxMDI2Nzg0NywicGF0aCI6Ii84MDIxMDEyLzMxMTc1MDQ0NC03MTRkMzc5NC1lMzg1LTRiNGQtYmM5Ni00ZDc1MDc4MmRhMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMTgyNDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTI3NWJiZGZhNDM1M2VhY2QyMTc5MGU0NDExNjYyMDUzMTFhYTA2Yjk0MDM0MjI2NjlkM2Y4NDc5OTcwNDdmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ynt3_bcrwwL-pilwbiOw1G63OtPTh9mXhZhznfCjUNw)

@rybchuk 
Thank you so much, I will definitely look into that as (there must be many output files), I will try and get back to you soon.
