### ISSUE TITLE
Refinement of 2D airfoil simulations

### ISSUE THREAD

**Issue by ET14** [Exawind/amr-wind#994]
Hello,
I am running 2D airfoil simulations in Amr-Wind using the FixedWingLine actuator module. By only defining in the y-direction a single LES gridpoint, unit width Ly and periodic BCs this setup allows for simulating a 2D airfoil in the x-z plane.
Since convergence of the results requires a very large domain, it would be desirable to refine the domain in the x and z coordinates, while keeping a single grid point in the y-direction.
Is there a way in Amr to specify different refinement ratios for different coordinate directions or is this fundamentally not allowed by the code structure?

Best,
Emanuel

**Comment by marchdf** [comment]
amrex currently doesn't support that (to the best of my knowledge). It is unfortunate that we don't have a true "2D" capability in amr-wind. We should probably add that to the backlog...

**Comment by tonyinme** [comment]
@ET14 , what happens when you try to refine your simulation using the standard refinement in a 2D mesh?

**Comment by ET14** [comment]
@tonyinme Then it cannot handle the single grid point in the y-direction when it tries to refine. The simulation does not crash, but all residuals are just zero.

**Comment by tonyinme** [comment]
@ET14 , thanks for explaining. 
@mbkuhn suggested that you can try running with 2 cells in the y direction and set the blocking factor in that direction to 2. 
That should be an almost 2D problem :) The gradients in the y direction should be zero, so I would not expect the code to do anything in that direction.

**Comment by marchdf** [comment]
@ET14 can you provide an update here or close this issue? thanks!
