### ISSUE TITLE
Warning while running (fastdisk/fastline) actuator method in AMR-Wind

### ISSUE THREAD

**Issue by AsimUdel** [Exawind/amr-wind#995]
I was getting a warning and then the simulation terminated while using actuator methods fast-disk and fast-line (NREL Wind turbines models ( https://github.com/NREL/openfast-turbine-models/tree/master/IEA-scaled)) in (AMR-Wind(1.0.0)+ OpenFAST (3.1.0)+ROSCO(2.9)), but when I changed( CompServo in .fst to 0) as Alex (suggested in https://github.com/rybchuk/amr-wind-tutorial/blob/main/03_turbines.md), simulation was running and completed successfully but warning was still there. 
Can someone tell me if is it with the specific version of ROSCO?  
I am attaching screenshots of both (warning+termination) and (warning only). P.S. I did not get any error while using (GUI in-built 5MW (no-servo) fastdisk/fastline actuator methods).
![with_CompServo=0](https://github.com/Exawind/amr-wind/assets/156853074/493ff9c4-a0f4-4fb1-9954-474c68c2a0f8)
![with_no_CompServo=0](https://github.com/Exawind/amr-wind/assets/156853074/4324f0d4-5772-4179-a821-5014bb62111a)

**Comment by marchdf** [comment]
I've seen this with ROSCO 2.9 (maybe 2.8?). Right now most the input files floating around are for ROSCO 2.7 so I recommend using that version. If you need ROSCO on frontier, then you need a flang-ed version of ROSCO. I maintain a branch of that here: https://github.com/marchdf/ROSCO/tree/rosco-27-flang

**Comment by rybchuk** [comment]
Two thoughts on potential ROSCO problems:
1. When you compile AMR-Wind and OpenFAST, you have certain modules loaded. Make sure those same modules loaded when you install ROSCO (Lawrence comments on that [here](/scratch/orybchuk/wakedynamics/bcs-ldm/palette_3d/experiments))
2. To confirm it's a ROSCO problem, you can test turning off the turbine controller by setting `CompServo = 0` in one of the `.fst` files

**Comment by AsimUdel** [comment]
@marchdf thank you so much, I will try to use that and will see what happens.

**Comment by AsimUdel** [comment]
@rybchuk , thank you so much, 
1) link (Lawrence comments) you have provided is not working can you please double check, but let me share e the details of dependencies/modules we loaded (while installing AMR-Wind-OpenFAST and ROSCO) , while installing/compiling (cmake, netcdf, intel oneapi, openmpi, mpi4py, ninja)
2) I have tried (CompServo =0, as you suggested in your tutorial) , my simulation ran (without termination) and completed successfully but warning was still there in the log file.

**Comment by lawrenceccheung** [comment]
Hi @AsimUdel,

Would you be able to post the servodyn and rosco discon files that you're using?  I haven't kept those files updated for the NREL 5MW turbine on the amrwind-frontend repo, so it might be useful to check the inputs for those files against the library versions that were compiled.

Thanks,

Lawrence
