### ISSUE TITLE
Virtual lidar test failing

### ISSUE THREAD

**Issue by tonyinme** [Exawind/amr-wind#998]
The [virtual lidar test](https://github.com/Exawind/amr-wind/tree/main/test/test_files/abl_virtual_lidar) is failing after the new [update](https://github.com/Exawind/amr-wind/pull/954) to the DTU Spinner sampler. 

It looks like the issue is related to the inputs and it should be an easy fix.

**Comment by mbkuhn** [comment]
fixed with PR #1000, which also updated the virtual lidar test
